/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Aplicacao;

import Modelo.Acao;
import com.google.gson.Gson;
import com.google.gson.reflect.TypeToken;
import javax.swing.Box;
import java.awt.Dimension;

import java.util.ArrayList;

import java.util.List;

import java.util.Collections;
import javax.swing.JFrame;
import javax.swing.SwingUtilities;

/**
 *
 * @author LENOVO
 */
public class AcoesEncontradas extends javax.swing.JFrame {


    /**
     * Creates new form PAgendamento
     */
    public AcoesEncontradas() {
        initComponents();
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        

    }
    
    public AcoesEncontradas(List<Acao> acoes) {
        initComponents();
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        this.setExtendedState(MAXIMIZED_BOTH);
        adicionarAcoes(acoes);

    }

    public void adicionarAcoes(List<Acao> acoes) {
        ordenarAcoes(acoes);
        for (Acao acao : acoes) {
            if (acao.getnSala() == -1) {
                AcoesPanel pa = new AcoesPanel(acao.getLogin(), acao.getTipoAcao(),
                        acao.dataFormatada(), acao.horaFormatada(), acao.getIdAcao());
                jPanelAcoes.add(pa);
            } else {
                AcoesPanel pa = new AcoesPanel(acao.getLogin(), acao.getTipoAcao(),
                        acao.dataFormatada(), acao.horaFormatada(), acao.getIdAcao(), acao.getnSala());
                jPanelAcoes.add(pa);
                
            }
        }

    }

    public void ordenarAcoes(List<Acao> acoes) {
        Collections.sort(acoes, (a1, a2) -> {
            int dataR = a2.getDataAcao().compareTo(a1.getDataAcao());
            if (dataR != 0) {
                return dataR;
            }
            return a2.getHoraAcao().compareTo(a1.getHoraAcao());
        });
    }

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPaneAcoes = new javax.swing.JScrollPane();
        jPanelAcoes = new javax.swing.JPanel();
        jLabelAgendamentos = new javax.swing.JLabel();
        jLabelIF1 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabelIfamLogo1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridLayout(1, 0));

        jPanel1.setBackground(new java.awt.Color(0, 51, 102));

        jScrollPaneAcoes.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPaneAcoes.setMaximumSize(new java.awt.Dimension(500, 32767));

        jPanelAcoes.setBackground(new java.awt.Color(0, 51, 102));
        jPanelAcoes.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanelAcoes.setLayout(new javax.swing.BoxLayout(jPanelAcoes, javax.swing.BoxLayout.Y_AXIS));

        jPanelAcoes.add(Box.createRigidArea(new Dimension(0,20)));

        jScrollPaneAcoes.setViewportView(jPanelAcoes);

        jLabelAgendamentos.setBackground(new java.awt.Color(255, 255, 255));
        jLabelAgendamentos.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 36)); // NOI18N
        jLabelAgendamentos.setForeground(new java.awt.Color(255, 255, 255));
        jLabelAgendamentos.setText("Ações encontradas");

        jLabelIF1.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 20)); // NOI18N
        jLabelIF1.setForeground(new java.awt.Color(255, 255, 255));
        jLabelIF1.setText("IFControl 3.0");

        jButton3.setBackground(new java.awt.Color(255, 51, 0));
        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton3.setText("SAIR");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabelIfamLogo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/IFAM_logo.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabelIfamLogo1))
                    .addComponent(jScrollPaneAcoes, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabelAgendamentos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabelIF1)))
                .addGap(27, 27, 27))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelIF1)
                    .addComponent(jLabelAgendamentos))
                .addGap(41, 41, 41)
                .addComponent(jScrollPaneAcoes, javax.swing.GroupLayout.DEFAULT_SIZE, 548, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelIfamLogo1, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        getContentPane().add(jPanel1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AcoesEncontradas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AcoesEncontradas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AcoesEncontradas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AcoesEncontradas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AcoesEncontradas().setVisible(true);
            }
        });
    }

    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabelAgendamentos;
    private javax.swing.JLabel jLabelIF1;
    private javax.swing.JLabel jLabelIfamLogo1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelAcoes;
    private javax.swing.JScrollPane jScrollPaneAcoes;
    // End of variables declaration//GEN-END:variables
}
