/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Aplicacao;

/**
 *
 * @author cauaa
 */
public class addAgendamentoFrame extends javax.swing.JFrame {

    /**
     * Creates new form g
     */
    public addAgendamentoFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTextFieldTitulo = new javax.swing.JTextField();
        jButtonAdd = new javax.swing.JButton();
        jLabelIF = new javax.swing.JLabel();
        jLabelIfamLogo = new javax.swing.JLabel();
        jLabelAdicionarAgendamento = new javax.swing.JLabel();
        jLabelTitulo = new javax.swing.JLabel();
        jLabelAte = new javax.swing.JLabel();
        jLabelDias = new javax.swing.JLabel();
        jLabelHorario = new javax.swing.JLabel();
        jLabelData = new javax.swing.JLabel();
        jRadioButtonSegunda = new javax.swing.JRadioButton();
        jRadioButtonTerca = new javax.swing.JRadioButton();
        jLabelDispositivos = new javax.swing.JLabel();
        jRadioButtonQuarta = new javax.swing.JRadioButton();
        jRadioButtonQuinta = new javax.swing.JRadioButton();
        jRadioButtonSexta = new javax.swing.JRadioButton();
        jRadioButtonSabado = new javax.swing.JRadioButton();
        jRadioButtonDomingo = new javax.swing.JRadioButton();
        jRadioButtonArCondicionado = new javax.swing.JRadioButton();
        jRadioButtonLuzes = new javax.swing.JRadioButton();
        jRadioButtonDataShow = new javax.swing.JRadioButton();
        jDataInicio = new com.toedter.calendar.JDateChooser();
        jDataFim = new com.toedter.calendar.JDateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 51, 102));

        jTextFieldTitulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldTituloActionPerformed(evt);
            }
        });

        jButtonAdd.setBackground(new java.awt.Color(0, 153, 51));
        jButtonAdd.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 12)); // NOI18N
        jButtonAdd.setForeground(new java.awt.Color(255, 255, 255));
        jButtonAdd.setText("Adicionar");
        jButtonAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddActionPerformed(evt);
            }
        });

        jLabelIF.setBackground(new java.awt.Color(187, 187, 187));
        jLabelIF.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 18)); // NOI18N
        jLabelIF.setForeground(new java.awt.Color(255, 255, 255));
        jLabelIF.setText("IFControl 3.0");

        jLabelIfamLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/IFAM_logo.png"))); // NOI18N
        jLabelIfamLogo.setText("jLabel1");

        jLabelAdicionarAgendamento.setBackground(new java.awt.Color(187, 187, 187));
        jLabelAdicionarAgendamento.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 24)); // NOI18N
        jLabelAdicionarAgendamento.setForeground(new java.awt.Color(255, 255, 255));
        jLabelAdicionarAgendamento.setText("Adicionar Agendamento");

        jLabelTitulo.setBackground(new java.awt.Color(255, 255, 255));
        jLabelTitulo.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 14)); // NOI18N
        jLabelTitulo.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTitulo.setText("Título");

        jLabelAte.setBackground(new java.awt.Color(255, 255, 255));
        jLabelAte.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 14)); // NOI18N
        jLabelAte.setForeground(new java.awt.Color(255, 255, 255));
        jLabelAte.setText("Até");

        jLabelDias.setBackground(new java.awt.Color(255, 255, 255));
        jLabelDias.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 14)); // NOI18N
        jLabelDias.setForeground(new java.awt.Color(255, 255, 255));
        jLabelDias.setText("Dias da Semana");

        jLabelHorario.setBackground(new java.awt.Color(255, 255, 255));
        jLabelHorario.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 14)); // NOI18N
        jLabelHorario.setForeground(new java.awt.Color(255, 255, 255));
        jLabelHorario.setText("Horário");

        jLabelData.setBackground(new java.awt.Color(255, 255, 255));
        jLabelData.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 14)); // NOI18N
        jLabelData.setForeground(new java.awt.Color(255, 255, 255));
        jLabelData.setText("Data");

        jRadioButtonSegunda.setText("S");

        jRadioButtonTerca.setText("T");
        jRadioButtonTerca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonTercaActionPerformed(evt);
            }
        });

        jLabelDispositivos.setBackground(new java.awt.Color(255, 255, 255));
        jLabelDispositivos.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 14)); // NOI18N
        jLabelDispositivos.setForeground(new java.awt.Color(255, 255, 255));
        jLabelDispositivos.setText("Dispositivos");

        jRadioButtonQuarta.setText("Q");
        jRadioButtonQuarta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonQuartaActionPerformed(evt);
            }
        });

        jRadioButtonQuinta.setText("Q");
        jRadioButtonQuinta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonQuintaActionPerformed(evt);
            }
        });

        jRadioButtonSexta.setText("S");
        jRadioButtonSexta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonSextaActionPerformed(evt);
            }
        });

        jRadioButtonSabado.setText("S");
        jRadioButtonSabado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonSabadoActionPerformed(evt);
            }
        });

        jRadioButtonDomingo.setText("D");
        jRadioButtonDomingo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonDomingoActionPerformed(evt);
            }
        });

        jRadioButtonArCondicionado.setText("Ar-Condicionado");

        jRadioButtonLuzes.setText("Luzes");
        jRadioButtonLuzes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonLuzesActionPerformed(evt);
            }
        });

        jRadioButtonDataShow.setText("DataShow");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelTitulo)
                    .addComponent(jLabelData))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(jLabelAdicionarAgendamento)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jDataInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                                        .addComponent(jLabelAte, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(32, 32, 32)
                                        .addComponent(jDataFim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jTextFieldTitulo))
                                .addGap(44, 44, 44))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelIF, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jButtonAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(175, 175, 175)
                                        .addComponent(jLabelIfamLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))))))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelHorario)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelDias)
                            .addComponent(jLabelDispositivos))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jRadioButtonArCondicionado)
                                .addGap(18, 18, 18)
                                .addComponent(jRadioButtonLuzes)
                                .addGap(18, 18, 18)
                                .addComponent(jRadioButtonDataShow))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jRadioButtonSegunda)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jRadioButtonTerca)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jRadioButtonQuarta)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jRadioButtonQuinta)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jRadioButtonSexta)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jRadioButtonSabado)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jRadioButtonDomingo)))))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelIF)
                .addGap(28, 28, 28)
                .addComponent(jLabelAdicionarAgendamento)
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelTitulo))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jDataInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelAte)
                            .addComponent(jDataFim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelData))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelDias)
                            .addComponent(jRadioButtonSegunda)
                            .addComponent(jRadioButtonTerca)
                            .addComponent(jRadioButtonQuarta)
                            .addComponent(jRadioButtonQuinta)
                            .addComponent(jRadioButtonSexta)
                            .addComponent(jRadioButtonSabado)
                            .addComponent(jRadioButtonDomingo))
                        .addGap(18, 18, 18)
                        .addComponent(jLabelHorario)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelDispositivos)
                            .addComponent(jRadioButtonArCondicionado)
                            .addComponent(jRadioButtonLuzes)
                            .addComponent(jRadioButtonDataShow))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabelIfamLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jButtonAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(41, 41, 41))))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 515, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 406, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldTituloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldTituloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldTituloActionPerformed

    private void jButtonAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonAddActionPerformed

    private void jRadioButtonTercaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonTercaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonTercaActionPerformed

    private void jRadioButtonQuartaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonQuartaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonQuartaActionPerformed

    private void jRadioButtonQuintaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonQuintaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonQuintaActionPerformed

    private void jRadioButtonSextaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonSextaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonSextaActionPerformed

    private void jRadioButtonSabadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonSabadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonSabadoActionPerformed

    private void jRadioButtonDomingoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonDomingoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonDomingoActionPerformed

    private void jRadioButtonLuzesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonLuzesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonLuzesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(addAgendamentoFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(addAgendamentoFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(addAgendamentoFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(addAgendamentoFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new addAgendamentoFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAdd;
    private com.toedter.calendar.JDateChooser jDataFim;
    private com.toedter.calendar.JDateChooser jDataInicio;
    private javax.swing.JLabel jLabelAdicionarAgendamento;
    private javax.swing.JLabel jLabelAte;
    private javax.swing.JLabel jLabelData;
    private javax.swing.JLabel jLabelDias;
    private javax.swing.JLabel jLabelDispositivos;
    private javax.swing.JLabel jLabelHorario;
    private javax.swing.JLabel jLabelIF;
    private javax.swing.JLabel jLabelIfamLogo;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButtonArCondicionado;
    private javax.swing.JRadioButton jRadioButtonDataShow;
    private javax.swing.JRadioButton jRadioButtonDomingo;
    private javax.swing.JRadioButton jRadioButtonLuzes;
    private javax.swing.JRadioButton jRadioButtonQuarta;
    private javax.swing.JRadioButton jRadioButtonQuinta;
    private javax.swing.JRadioButton jRadioButtonSabado;
    private javax.swing.JRadioButton jRadioButtonSegunda;
    private javax.swing.JRadioButton jRadioButtonSexta;
    private javax.swing.JRadioButton jRadioButtonTerca;
    private javax.swing.JTextField jTextFieldTitulo;
    // End of variables declaration//GEN-END:variables
}
