/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Aplicacao;

import Modelo.Agendamento;
import com.toedter.calendar.JDateChooser;
import java.sql.Time;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import javax.swing.JRadioButton;
import javax.swing.JSpinner;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
/**
 *
 * @author cauaa
 */
public class addAgendamentoFrame extends javax.swing.JFrame {

    /**
     * Creates new form g
     */
    public addAgendamentoFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonCancelar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jTextFieldTitulo = new javax.swing.JTextField();
        jButtonAdd = new javax.swing.JButton();
        jLabelIF = new javax.swing.JLabel();
        jLabelIfamLogo = new javax.swing.JLabel();
        jLabelAdicionarAgendamento = new javax.swing.JLabel();
        jLabelTitulo = new javax.swing.JLabel();
        jLabelAte = new javax.swing.JLabel();
        jLabelDias = new javax.swing.JLabel();
        jLabelHoraIn = new javax.swing.JLabel();
        jLabelData = new javax.swing.JLabel();
        jRadioButtonSegunda = new javax.swing.JRadioButton();
        jRadioButtonTerca = new javax.swing.JRadioButton();
        jLabelDispositivos = new javax.swing.JLabel();
        jRadioButtonQuarta = new javax.swing.JRadioButton();
        jRadioButtonQuinta = new javax.swing.JRadioButton();
        jRadioButtonSexta = new javax.swing.JRadioButton();
        jRadioButtonSabado = new javax.swing.JRadioButton();
        jRadioButtonDomingo = new javax.swing.JRadioButton();
        jRadioButtonArCondicionado = new javax.swing.JRadioButton();
        jRadioButtonLuzes = new javax.swing.JRadioButton();
        jRadioButtonDataShow = new javax.swing.JRadioButton();
        jDataInicio = new com.toedter.calendar.JDateChooser();
        jDataFim = new com.toedter.calendar.JDateChooser();
        jSpinnerHoraIn = new javax.swing.JSpinner();
        jLabelSeparatorHoraIn = new javax.swing.JLabel();
        jSpinnerMinutosIn = new javax.swing.JSpinner();
        jLabelHoraFim = new javax.swing.JLabel();
        jSpinnerHoraFim = new javax.swing.JSpinner();
        jLabelSeparatorHoraFim = new javax.swing.JLabel();
        jSpinnerMinutosFim = new javax.swing.JSpinner();
        jButtonCancelar1 = new javax.swing.JButton();
        jLabelSalas = new javax.swing.JLabel();
        jTextFieldSalas = new javax.swing.JTextField();
        jLabelDesc1 = new javax.swing.JLabel();
        jLabelDesc2 = new javax.swing.JLabel();

        jButtonCancelar.setBackground(new java.awt.Color(0, 51, 102));
        jButtonCancelar.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 12)); // NOI18N
        jButtonCancelar.setForeground(new java.awt.Color(255, 255, 255));
        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridLayout());

        jPanel1.setBackground(new java.awt.Color(0, 51, 102));

        jTextFieldTitulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldTituloActionPerformed(evt);
            }
        });

        jButtonAdd.setBackground(new java.awt.Color(0, 153, 51));
        jButtonAdd.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 12)); // NOI18N
        jButtonAdd.setForeground(new java.awt.Color(255, 255, 255));
        jButtonAdd.setText("Adicionar");
        jButtonAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddActionPerformed(evt);
            }
        });

        jLabelIF.setBackground(new java.awt.Color(187, 187, 187));
        jLabelIF.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 18)); // NOI18N
        jLabelIF.setForeground(new java.awt.Color(255, 255, 255));
        jLabelIF.setText("IFControl 3.0");

        jLabelIfamLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/IFAM_logo.png"))); // NOI18N
        jLabelIfamLogo.setText("jLabel1");

        jLabelAdicionarAgendamento.setBackground(new java.awt.Color(187, 187, 187));
        jLabelAdicionarAgendamento.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 24)); // NOI18N
        jLabelAdicionarAgendamento.setForeground(new java.awt.Color(255, 255, 255));
        jLabelAdicionarAgendamento.setText("Adicionar Agendamento");

        jLabelTitulo.setBackground(new java.awt.Color(255, 255, 255));
        jLabelTitulo.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 14)); // NOI18N
        jLabelTitulo.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTitulo.setText("Título");

        jLabelAte.setBackground(new java.awt.Color(255, 255, 255));
        jLabelAte.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 14)); // NOI18N
        jLabelAte.setForeground(new java.awt.Color(255, 255, 255));
        jLabelAte.setText("Até");

        jLabelDias.setBackground(new java.awt.Color(255, 255, 255));
        jLabelDias.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 14)); // NOI18N
        jLabelDias.setForeground(new java.awt.Color(255, 255, 255));
        jLabelDias.setText("Dias da Semana");

        jLabelHoraIn.setBackground(new java.awt.Color(255, 255, 255));
        jLabelHoraIn.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 14)); // NOI18N
        jLabelHoraIn.setForeground(new java.awt.Color(255, 255, 255));
        jLabelHoraIn.setText("Hora Início");

        jLabelData.setBackground(new java.awt.Color(255, 255, 255));
        jLabelData.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 14)); // NOI18N
        jLabelData.setForeground(new java.awt.Color(255, 255, 255));
        jLabelData.setText("Data");

        jRadioButtonSegunda.setText("S");
        jRadioButtonSegunda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonSegundaActionPerformed(evt);
            }
        });

        jRadioButtonTerca.setText("T");
        jRadioButtonTerca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonTercaActionPerformed(evt);
            }
        });

        jLabelDispositivos.setBackground(new java.awt.Color(255, 255, 255));
        jLabelDispositivos.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 14)); // NOI18N
        jLabelDispositivos.setForeground(new java.awt.Color(255, 255, 255));
        jLabelDispositivos.setText("Dispositivos");

        jRadioButtonQuarta.setText("Q");
        jRadioButtonQuarta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonQuartaActionPerformed(evt);
            }
        });

        jRadioButtonQuinta.setText("Q");
        jRadioButtonQuinta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonQuintaActionPerformed(evt);
            }
        });

        jRadioButtonSexta.setText("S");
        jRadioButtonSexta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonSextaActionPerformed(evt);
            }
        });

        jRadioButtonSabado.setText("S");
        jRadioButtonSabado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonSabadoActionPerformed(evt);
            }
        });

        jRadioButtonDomingo.setText("D");
        jRadioButtonDomingo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonDomingoActionPerformed(evt);
            }
        });

        jRadioButtonArCondicionado.setText("Ar-Condicionado");

        jRadioButtonLuzes.setText("Luzes");
        jRadioButtonLuzes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonLuzesActionPerformed(evt);
            }
        });

        jRadioButtonDataShow.setText("DataShow");

        jSpinnerHoraIn.setModel(new javax.swing.SpinnerNumberModel(0, 0, 23, 1));

        jLabelSeparatorHoraIn.setBackground(new java.awt.Color(255, 255, 255));
        jLabelSeparatorHoraIn.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 14)); // NOI18N
        jLabelSeparatorHoraIn.setForeground(new java.awt.Color(255, 255, 255));
        jLabelSeparatorHoraIn.setText(":");

        jSpinnerMinutosIn.setModel(new javax.swing.SpinnerNumberModel(0, 0, 23, 1));

        jLabelHoraFim.setBackground(new java.awt.Color(255, 255, 255));
        jLabelHoraFim.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 14)); // NOI18N
        jLabelHoraFim.setForeground(new java.awt.Color(255, 255, 255));
        jLabelHoraFim.setText("Hora Fim");

        jSpinnerHoraFim.setModel(new javax.swing.SpinnerNumberModel(0, 0, 23, 1));

        jLabelSeparatorHoraFim.setBackground(new java.awt.Color(255, 255, 255));
        jLabelSeparatorHoraFim.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 14)); // NOI18N
        jLabelSeparatorHoraFim.setForeground(new java.awt.Color(255, 255, 255));
        jLabelSeparatorHoraFim.setText(":");

        jSpinnerMinutosFim.setModel(new javax.swing.SpinnerNumberModel(0, 0, 23, 1));

        jButtonCancelar1.setBackground(new java.awt.Color(0, 51, 102));
        jButtonCancelar1.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 12)); // NOI18N
        jButtonCancelar1.setForeground(new java.awt.Color(255, 255, 255));
        jButtonCancelar1.setText("Cancelar");
        jButtonCancelar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelar1ActionPerformed(evt);
            }
        });

        jLabelSalas.setBackground(new java.awt.Color(255, 255, 255));
        jLabelSalas.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 14)); // NOI18N
        jLabelSalas.setForeground(new java.awt.Color(255, 255, 255));
        jLabelSalas.setText("Salas");

        jTextFieldSalas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldSalasActionPerformed(evt);
            }
        });

        jLabelDesc1.setText("Em salas diferentes separe com \",\" Exemplo: \"1, 3, 6\"");

        jLabelDesc2.setText("Em salas sequenciais utilizar \"-\" Exemplo: \"1-3\"");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(210, 210, 210)
                .addComponent(jLabelAdicionarAgendamento)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabelData)
                        .addGap(40, 40, 40)
                        .addComponent(jDataInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabelAte, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jDataFim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelDias)
                            .addComponent(jLabelHoraIn))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jRadioButtonSegunda)
                                .addGap(18, 18, 18)
                                .addComponent(jRadioButtonTerca)
                                .addGap(18, 18, 18)
                                .addComponent(jRadioButtonQuarta)
                                .addGap(18, 18, 18)
                                .addComponent(jRadioButtonQuinta)
                                .addGap(18, 18, 18)
                                .addComponent(jRadioButtonSexta)
                                .addGap(18, 18, 18)
                                .addComponent(jRadioButtonSabado))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jSpinnerHoraIn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabelSeparatorHoraIn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jSpinnerMinutosIn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(28, 28, 28)
                                .addComponent(jLabelHoraFim)
                                .addGap(5, 5, 5)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jSpinnerHoraFim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabelSeparatorHoraFim)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSpinnerMinutosFim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(110, 110, 110))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jRadioButtonDomingo)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabelIF))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jButtonCancelar1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(251, 251, 251)
                        .addComponent(jLabelIfamLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabelDispositivos)
                        .addGap(36, 36, 36)
                        .addComponent(jRadioButtonArCondicionado)
                        .addGap(18, 18, 18)
                        .addComponent(jRadioButtonLuzes)
                        .addGap(18, 18, 18)
                        .addComponent(jRadioButtonDataShow)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabelTitulo)
                        .addGap(32, 32, 32)
                        .addComponent(jTextFieldTitulo)
                        .addGap(44, 44, 44))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabelSalas)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                        .addComponent(jTextFieldSalas, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelDesc2, javax.swing.GroupLayout.PREFERRED_SIZE, 371, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelDesc1, javax.swing.GroupLayout.PREFERRED_SIZE, 371, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(14, 14, 14))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelIF)
                .addGap(43, 43, 43)
                .addComponent(jLabelAdicionarAgendamento)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelTitulo))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jDataInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabelData)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(jDataFim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(50, 50, 50)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabelDias)
                                    .addComponent(jRadioButtonSegunda)
                                    .addComponent(jRadioButtonTerca)
                                    .addComponent(jRadioButtonQuarta)
                                    .addComponent(jRadioButtonQuinta)
                                    .addComponent(jRadioButtonSexta)
                                    .addComponent(jRadioButtonSabado)
                                    .addComponent(jRadioButtonDomingo))
                                .addGap(28, 28, 28))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabelAte)
                                .addGap(99, 99, 99)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabelHoraIn)
                                .addComponent(jSpinnerHoraIn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabelSeparatorHoraIn)
                                .addComponent(jSpinnerMinutosIn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabelHoraFim))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jSpinnerHoraFim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabelSeparatorHoraFim)
                                .addComponent(jSpinnerMinutosFim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(45, 45, 45)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelDispositivos)
                            .addComponent(jRadioButtonArCondicionado)
                            .addComponent(jRadioButtonLuzes)
                            .addComponent(jRadioButtonDataShow))
                        .addGap(30, 30, 30)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelSalas)
                    .addComponent(jTextFieldSalas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelDesc1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelDesc2)
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabelIfamLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonCancelar1))
                        .addGap(41, 41, 41))))
        );

        getContentPane().add(jPanel1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioButtonLuzesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonLuzesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonLuzesActionPerformed

    private void jRadioButtonDomingoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonDomingoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonDomingoActionPerformed

    private void jRadioButtonSabadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonSabadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonSabadoActionPerformed

    private void jRadioButtonSextaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonSextaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonSextaActionPerformed

    private void jRadioButtonQuintaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonQuintaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonQuintaActionPerformed

    private void jRadioButtonQuartaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonQuartaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonQuartaActionPerformed

    private void jRadioButtonTercaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonTercaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonTercaActionPerformed

    private void jRadioButtonSegundaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonSegundaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonSegundaActionPerformed

    private void jButtonAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddActionPerformed
        // Cria uma nova instância do modelo
        Agendamento novoAgendamento = new Agendamento();

        // 1. Título
        novoAgendamento.setTitulo(jTextFieldTitulo.getText());

        // O campo de salas no seu código está como jTextFieldTitulo1
        // É altamente recomendado renomear para algo como jTextFieldSalas no NetBeans!
        String salasStr = jTextFieldSalas.getText();

        // 2. Datas (JDateChooser)
        if (jDataInicio.getCalendar() != null) {
            novoAgendamento.setDataIn(jDataInicio.getCalendar());
        }
        if (jDataFim.getCalendar() != null) {
            novoAgendamento.setDataF(jDataFim.getCalendar());
        }

        // 3. Dias da Semana (JRadioButtons)
        novoAgendamento.setDiaSemana(coletarDiasDaSemana());

        // 4. Horários (JSpinner)
        novoAgendamento.sethAtv(coletarHora(jSpinnerHoraIn, jSpinnerMinutosIn));
        novoAgendamento.sethDesat(coletarHora(jSpinnerHoraFim, jSpinnerMinutosFim));

        // 5. Dispositivos (JRadioButtons - Múltipla Seleção)
        JRadioButton[] chkDispositivos = {jRadioButtonArCondicionado, jRadioButtonLuzes, jRadioButtonDataShow};
        novoAgendamento.setDispositivos(coletarDispositivos(chkDispositivos));

        // 6. Salas (JTextField)
        try {
            novoAgendamento.setSalas(analisarStringSalas(salasStr));
        } catch (NumberFormatException e) {
            // Exibir erro para o usuário, ex: JOptionPane.showMessageDialog(this, "Erro no formato das Salas.");
            System.err.println("Erro de formato de salas: " + e.getMessage());
            return;
        }

        // A partir daqui, o objeto 'novoAgendamento' está preenchido e pronto para ser usado (ex: salvar no DB)
        System.out.println("Agendamento criado e pronto para salvar: " + novoAgendamento.toString());
    }//GEN-LAST:event_jButtonAddActionPerformed

    private void jTextFieldTituloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldTituloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldTituloActionPerformed

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        dispose();
    }//GEN-LAST:event_jButtonCancelarActionPerformed

    private void jButtonCancelar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelar1ActionPerformed
        dispose();
    }//GEN-LAST:event_jButtonCancelar1ActionPerformed

    private void jTextFieldSalasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldSalasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldSalasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(addAgendamentoFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(addAgendamentoFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(addAgendamentoFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(addAgendamentoFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new addAgendamentoFrame().setVisible(true);
            }
        });
    }

    private int[] coletarDiasDaSemana() {
        ArrayList<Integer> diasSelecionados = new ArrayList<>();

        // Mapeia os JRadioButtons na ordem: Dom, Seg, Ter, Qua, Qui, Sex, Sáb
        JRadioButton[] dias = {jRadioButtonDomingo, jRadioButtonSegunda, jRadioButtonTerca, jRadioButtonQuarta,
            jRadioButtonQuinta, jRadioButtonSexta, jRadioButtonSabado};

        // Mapeamento para os valores de Calendar: 1=DOMINGO, 2=SEGUNDA, ..., 7=SABADO
        int[] calendarDays = {Calendar.SUNDAY, Calendar.MONDAY, Calendar.TUESDAY, Calendar.WEDNESDAY,
            Calendar.THURSDAY, Calendar.FRIDAY, Calendar.SATURDAY};

        for (int i = 0; i < dias.length; i++) {
            if (dias[i].isSelected()) {
                diasSelecionados.add(calendarDays[i]);
            }
        }

        return diasSelecionados.stream().mapToInt(i -> i).toArray();
    }

    /**
     * Cria um objeto Time a partir dos valores de hora e minuto de dois
     * Spinners.
     */
    private Time coletarHora(JSpinner spinnerHora, JSpinner spinnerMinuto) {
        // Certifique-se de que os Spinners têm modelos de número
        int hora = (int) spinnerHora.getValue();
        int minuto = (int) spinnerMinuto.getValue();

        Calendar cal = Calendar.getInstance();
        cal.set(Calendar.HOUR_OF_DAY, hora);
        cal.set(Calendar.MINUTE, minuto);
        cal.set(Calendar.SECOND, 0);
        cal.set(Calendar.MILLISECOND, 0);

        // Retorna a hora como java.sql.Time
        return new Time(cal.getTimeInMillis());
    }

    /**
     * Coleta o texto de todos os JRadioButtons de dispositivos selecionados.
     */
    private ArrayList<String> coletarDispositivos(JRadioButton[] radiobuttons) {
        ArrayList<String> dispositivos = new ArrayList<>();
        for (JRadioButton rb : radiobuttons) {
            if (rb.isSelected()) {
                dispositivos.add(rb.getText());
            }
        }
        return dispositivos;
    }

    /**
     * Analisa a string de salas ("1, 3, 6" ou "1-3") e retorna um array de
     * inteiros. (Esta lógica não precisa de alteração, pois é independente do
     * tipo de componente.)
     */
    private int[] analisarStringSalas(String salasStr) throws NumberFormatException {
        if (salasStr == null || salasStr.trim().isEmpty()) {
            return new int[0];
        }

        salasStr = salasStr.replaceAll("\\s+", ""); // Remove espaços em branco
        ArrayList<Integer> salas = new ArrayList<>();

        String[] partes = salasStr.split(",");

        for (String parte : partes) {
            if (parte.contains("-")) {
                // Caso de range: "1-3"
                String[] range = parte.split("-");
                if (range.length == 2) {
                    try {
                        int inicio = Integer.parseInt(range[0]);
                        int fim = Integer.parseInt(range[1]);
                        for (int i = inicio; i <= fim; i++) {
                            salas.add(i);
                        }
                    } catch (NumberFormatException e) {
                        throw new NumberFormatException("Formato de range inválido na parte: " + parte);
                    }
                } else {
                    throw new NumberFormatException("Formato de range incompleto: " + parte);
                }
            } else {
                // Caso de número único: "3"
                try {
                    salas.add(Integer.parseInt(parte));
                } catch (NumberFormatException e) {
                    throw new NumberFormatException("Número de sala inválido: " + parte);
                }
            }
        }

        // Converte a ArrayList para int[] e retorna
        return salas.stream().mapToInt(i -> i).toArray();
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAdd;
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonCancelar1;
    private com.toedter.calendar.JDateChooser jDataFim;
    private com.toedter.calendar.JDateChooser jDataInicio;
    private javax.swing.JLabel jLabelAdicionarAgendamento;
    private javax.swing.JLabel jLabelAte;
    private javax.swing.JLabel jLabelData;
    private javax.swing.JLabel jLabelDesc1;
    private javax.swing.JLabel jLabelDesc2;
    private javax.swing.JLabel jLabelDias;
    private javax.swing.JLabel jLabelDispositivos;
    private javax.swing.JLabel jLabelHoraFim;
    private javax.swing.JLabel jLabelHoraIn;
    private javax.swing.JLabel jLabelIF;
    private javax.swing.JLabel jLabelIfamLogo;
    private javax.swing.JLabel jLabelSalas;
    private javax.swing.JLabel jLabelSeparatorHoraFim;
    private javax.swing.JLabel jLabelSeparatorHoraIn;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButtonArCondicionado;
    private javax.swing.JRadioButton jRadioButtonDataShow;
    private javax.swing.JRadioButton jRadioButtonDomingo;
    private javax.swing.JRadioButton jRadioButtonLuzes;
    private javax.swing.JRadioButton jRadioButtonQuarta;
    private javax.swing.JRadioButton jRadioButtonQuinta;
    private javax.swing.JRadioButton jRadioButtonSabado;
    private javax.swing.JRadioButton jRadioButtonSegunda;
    private javax.swing.JRadioButton jRadioButtonSexta;
    private javax.swing.JRadioButton jRadioButtonTerca;
    private javax.swing.JSpinner jSpinnerHoraFim;
    private javax.swing.JSpinner jSpinnerHoraIn;
    private javax.swing.JSpinner jSpinnerMinutosFim;
    private javax.swing.JSpinner jSpinnerMinutosIn;
    private javax.swing.JTextField jTextFieldSalas;
    private javax.swing.JTextField jTextFieldTitulo;
    // End of variables declaration//GEN-END:variables
}
