/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Aplicacao;

import Modelo.CodIr;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author cauaa
 */
public class AddCodigosAr extends javax.swing.JFrame {
    private HashMap<String, String> verListaCod;
    private static List<CodIr> ListaCod;
    private boolean completou = false;
    /**
     * Creates new form g
     */
    public AddCodigosAr() {
        initComponents();
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        ListaCod = new ArrayList<>();
        verListaCod = new HashMap<>();
    }
    
    public AddCodigosAr(List<CodIr> codigos) {
        initComponents();
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        ListaCod = new ArrayList<>();
        
        verListaCod = new HashMap<>();
        for(CodIr cod:codigos){
            verListaCod.put(cod.getFuncao(), cod.getCod());
        }
    }

    public List<CodIr> getListaCod() {
        return ListaCod;
    }

    public boolean isCompletou() {
        return completou;
    }
    
    public void terminar() {
        for (Map.Entry<String, String> entry : verListaCod.entrySet()) {
            CodIr cod=new CodIr();
            cod.setFuncao(entry.getKey());
            cod.setCod(entry.getValue());
            ListaCod.add(cod);
        }
        completou=true;
        setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButtonCompletar = new javax.swing.JButton();
        jLabelIF = new javax.swing.JLabel();
        jLabelIfamLogo = new javax.swing.JLabel();
        jLabelAdicionarDispositivo = new javax.swing.JLabel();
        jButtonAdd = new javax.swing.JButton();
        jTextFieldCod = new javax.swing.JTextField();
        comboBoxModo = new javax.swing.JComboBox<>();
        comboBoxTemperatura = new javax.swing.JComboBox<>();
        jLabelSeparatorHoraFim = new javax.swing.JLabel();
        jLabelDesc1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridLayout(1, 0));

        jPanel1.setBackground(new java.awt.Color(0, 51, 102));

        jButtonCompletar.setBackground(new java.awt.Color(0, 153, 51));
        jButtonCompletar.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 12)); // NOI18N
        jButtonCompletar.setForeground(new java.awt.Color(255, 255, 255));
        jButtonCompletar.setText("Completar");
        jButtonCompletar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCompletarActionPerformed(evt);
            }
        });

        jLabelIF.setBackground(new java.awt.Color(187, 187, 187));
        jLabelIF.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 18)); // NOI18N
        jLabelIF.setForeground(new java.awt.Color(255, 255, 255));
        jLabelIF.setText("IFControl 3.0");

        jLabelIfamLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/IFAM_logo.png"))); // NOI18N
        jLabelIfamLogo.setText("jLabel1");

        jLabelAdicionarDispositivo.setBackground(new java.awt.Color(187, 187, 187));
        jLabelAdicionarDispositivo.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 24)); // NOI18N
        jLabelAdicionarDispositivo.setForeground(new java.awt.Color(255, 255, 255));
        jLabelAdicionarDispositivo.setText("Adicionar Codigos");

        jButtonAdd.setBackground(new java.awt.Color(255, 102, 0));
        jButtonAdd.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 12)); // NOI18N
        jButtonAdd.setForeground(new java.awt.Color(255, 255, 255));
        jButtonAdd.setText("Add");
        jButtonAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddActionPerformed(evt);
            }
        });

        jTextFieldCod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCodActionPerformed(evt);
            }
        });

        comboBoxModo.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 14)); // NOI18N
        comboBoxModo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cool", "Fan", "Auto", "Dry", "ON", "OFF" }));
        comboBoxModo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxModoActionPerformed(evt);
            }
        });

        comboBoxTemperatura.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 14)); // NOI18N
        comboBoxTemperatura.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30" }));
        comboBoxTemperatura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxTemperaturaActionPerformed(evt);
            }
        });

        jLabelSeparatorHoraFim.setBackground(new java.awt.Color(255, 255, 255));
        jLabelSeparatorHoraFim.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 14)); // NOI18N
        jLabelSeparatorHoraFim.setForeground(new java.awt.Color(255, 255, 255));
        jLabelSeparatorHoraFim.setText(":");

        jLabelDesc1.setBackground(new java.awt.Color(255, 255, 255));
        jLabelDesc1.setForeground(new java.awt.Color(255, 255, 255));
        jLabelDesc1.setText("Ao escolher o modo AUTO, FAN, ON ou OFF não é necessario mudar a temperatura");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(345, Short.MAX_VALUE)
                .addComponent(jButtonCompletar, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(271, 271, 271))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabelIfamLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(comboBoxModo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(comboBoxTemperatura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelSeparatorHoraFim)
                        .addGap(7, 7, 7)
                        .addComponent(jTextFieldCod)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelIF)
                            .addComponent(jButtonAdd)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabelDesc1)
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(242, 242, 242)
                .addComponent(jLabelAdicionarDispositivo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelIF)
                .addGap(41, 41, 41)
                .addComponent(jLabelAdicionarDispositivo)
                .addGap(48, 48, 48)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonAdd)
                    .addComponent(jTextFieldCod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboBoxModo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboBoxTemperatura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelSeparatorHoraFim))
                .addGap(18, 18, 18)
                .addComponent(jLabelDesc1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addComponent(jButtonCompletar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addComponent(jLabelIfamLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );

        getContentPane().add(jPanel1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCompletarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCompletarActionPerformed
       if (verListaCod.size() == 0) {
            int resposta = JOptionPane.showConfirmDialog(
                    null, // Componente pai (null para centrar na tela)
                    "Nem um cod ir adicionado; Deseja procesguir?", // A mensagem a ser exibida
                    "Deseja?", // O título da janela
                    JOptionPane.YES_NO_OPTION, // As opções de botões (Sim e Não)
                    JOptionPane.QUESTION_MESSAGE // O ícone da caixa de diálogo

            );
            if (resposta == JOptionPane.YES_OPTION) {
                terminar();
            }
        }else if(verListaCod.size()<32){
            int resposta = JOptionPane.showConfirmDialog(
                    null, // Componente pai (null para centrar na tela)
                    "Falta mais codigos; Deseja procesguir?", // A mensagem a ser exibida
                    "Deseja?", // O título da janela
                    JOptionPane.YES_NO_OPTION, // As opções de botões (Sim e Não)
                    JOptionPane.QUESTION_MESSAGE // O ícone da caixa de diálogo

            );
            if (resposta == JOptionPane.YES_OPTION) {
                terminar();
            }
        }else{
            JOptionPane.showMessageDialog(null, "Codigos adicionados com sucesso", "Sucesso", JOptionPane.INFORMATION_MESSAGE);
            terminar();
        }
    }//GEN-LAST:event_jButtonCompletarActionPerformed

    private void jButtonAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddActionPerformed
        // TODO add your handling code here:
        String modo=(String) comboBoxModo.getSelectedItem();
        String funcao;
        if(modo.contains("ON")||modo.contains("OFF")||modo.contains("Auto")||modo.contains("Fan")){
            funcao=modo;
        }else{
            funcao = (String) modo + comboBoxTemperatura.getSelectedItem();
        }
       
        String cod = jTextFieldCod.getText();
        if (verListaCod.containsKey(funcao)) {
            int resposta = JOptionPane.showConfirmDialog(
                    null, // Componente pai (null para centrar na tela)
                    "Deseja modificar o cod ir da funcao " + funcao, // A mensagem a ser exibida
                    "Deseja?", // O título da janela
                    JOptionPane.YES_NO_OPTION, // As opções de botões (Sim e Não)
                    JOptionPane.QUESTION_MESSAGE // O ícone da caixa de diálogo
            );
            if (resposta == JOptionPane.YES_OPTION) {
                verListaCod.put(funcao, cod);
                JOptionPane.showMessageDialog(null, "Editado: "+funcao, "Sucesso", JOptionPane.INFORMATION_MESSAGE);
            }
        } else {
            verListaCod.put(funcao, cod);
            JOptionPane.showMessageDialog(null, "Adicionado: "+funcao, "Sucesso", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_jButtonAddActionPerformed

    private void jTextFieldCodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCodActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCodActionPerformed

    private void comboBoxModoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxModoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboBoxModoActionPerformed

    private void comboBoxTemperaturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxTemperaturaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboBoxTemperaturaActionPerformed


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddCodigosAr.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddCodigosAr.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddCodigosAr.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddCodigosAr.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddCodigosAr().setVisible(true);
            }
        });
    }    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> comboBoxModo;
    private javax.swing.JComboBox<String> comboBoxTemperatura;
    private javax.swing.JButton jButtonAdd;
    private javax.swing.JButton jButtonCompletar;
    private javax.swing.JLabel jLabelAdicionarDispositivo;
    private javax.swing.JLabel jLabelDesc1;
    private javax.swing.JLabel jLabelIF;
    private javax.swing.JLabel jLabelIfamLogo;
    private javax.swing.JLabel jLabelSeparatorHoraFim;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextFieldCod;
    // End of variables declaration//GEN-END:variables
}
