/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Aplicacao;

/**
 *
 * @author LENOVO
 */
public class AgendamentoPanel extends javax.swing.JPanel {

    /**
     * Creates new form AgendamentoPanel
     */
    public AgendamentoPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        jLabelAutor = new javax.swing.JLabel();
        jLabelInicio = new javax.swing.JLabel();
        jLabelFim = new javax.swing.JLabel();
        jButtonEditar = new javax.swing.JButton();
        jLabelTitulo = new javax.swing.JLabel();
        jLabelAutorEd = new javax.swing.JLabel();
        jLabelTituloEd = new javax.swing.JLabel();
        jLabelInicioEd = new javax.swing.JLabel();
        jLabelFimEd = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jPanel3 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jRadioButtonSegunda = new javax.swing.JRadioButton();
        jRadioButtonTerca = new javax.swing.JRadioButton();
        jRadioButtonQuarta = new javax.swing.JRadioButton();
        jRadioButtonQuinta = new javax.swing.JRadioButton();
        jRadioButtonSexta = new javax.swing.JRadioButton();
        jRadioButtonSabado = new javax.swing.JRadioButton();
        jRadioButtonDomingo = new javax.swing.JRadioButton();
        jPanel5 = new javax.swing.JPanel();
        jRadioButton8 = new javax.swing.JRadioButton();
        jRadioButton9 = new javax.swing.JRadioButton();
        jRadioButton10 = new javax.swing.JRadioButton();
        jButton4 = new javax.swing.JButton();
        jLabelhoraAtiv = new javax.swing.JLabel();
        jLabelhoraDesativ = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jLabelhoraAtivEd = new javax.swing.JLabel();
        jLabelhoraDesativEd = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jLabelSalas = new javax.swing.JLabel();
        jLabelSalasEd = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();

        setBackground(new java.awt.Color(153, 153, 153));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        setMaximumSize(new java.awt.Dimension(800, 120));
        setPreferredSize(new java.awt.Dimension(1062, 80));

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jLabelAutor.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 14)); // NOI18N
        jLabelAutor.setForeground(new java.awt.Color(0, 0, 0));
        jLabelAutor.setText("Autor:");

        jLabelInicio.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 14)); // NOI18N
        jLabelInicio.setForeground(new java.awt.Color(0, 0, 0));
        jLabelInicio.setText("Inicio:");

        jLabelFim.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 14)); // NOI18N
        jLabelFim.setForeground(new java.awt.Color(0, 0, 0));
        jLabelFim.setText("Fim:");

        jButtonEditar.setBackground(new java.awt.Color(153, 153, 153));
        jButtonEditar.setForeground(new java.awt.Color(0, 0, 0));
        jButtonEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/editar.png"))); // NOI18N
        jButtonEditar.setBorder(null);
        jButtonEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditarActionPerformed(evt);
            }
        });

        jLabelTitulo.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 14)); // NOI18N
        jLabelTitulo.setForeground(new java.awt.Color(0, 0, 0));
        jLabelTitulo.setText("Titulo:");

        jLabelAutorEd.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 14)); // NOI18N
        jLabelAutorEd.setForeground(new java.awt.Color(0, 0, 0));
        jLabelAutorEd.setText("XXXXXXXXX");

        jLabelTituloEd.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 14)); // NOI18N
        jLabelTituloEd.setForeground(new java.awt.Color(0, 0, 0));
        jLabelTituloEd.setText("XXXXXXXXX");

        jLabelInicioEd.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 14)); // NOI18N
        jLabelInicioEd.setForeground(new java.awt.Color(0, 0, 0));
        jLabelInicioEd.setText("XXXXXXXXX");

        jLabelFimEd.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 14)); // NOI18N
        jLabelFimEd.setForeground(new java.awt.Color(0, 0, 0));
        jLabelFimEd.setText("XXXXXXXXX");

        jSeparator2.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jPanel3.setBackground(new java.awt.Color(153, 153, 153));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel3.setPreferredSize(new java.awt.Dimension(50, 50));
        jPanel3.setLayout(new java.awt.GridLayout(2, 1));

        jLabel6.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText(" S    T   Q   Q   S   S   D");
        jPanel3.add(jLabel6);

        jPanel4.setBackground(new java.awt.Color(153, 153, 153));
        jPanel4.setPreferredSize(new java.awt.Dimension(50, 25));
        jPanel4.setLayout(new java.awt.GridLayout(1, 7, 5, 0));

        jRadioButtonSegunda.setPreferredSize(new java.awt.Dimension(10, 20));
        jRadioButtonSegunda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonSegundaActionPerformed(evt);
            }
        });
        jPanel4.add(jRadioButtonSegunda);
        jPanel4.add(jRadioButtonTerca);
        jPanel4.add(jRadioButtonQuarta);
        jPanel4.add(jRadioButtonQuinta);
        jPanel4.add(jRadioButtonSexta);
        jPanel4.add(jRadioButtonSabado);
        jPanel4.add(jRadioButtonDomingo);

        jPanel3.add(jPanel4);

        jPanel5.setBackground(new java.awt.Color(153, 153, 153));
        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel5.setMinimumSize(new java.awt.Dimension(70, 50));
        jPanel5.setPreferredSize(new java.awt.Dimension(25, 25));
        jPanel5.setLayout(new java.awt.GridLayout(2, 2));

        jRadioButton8.setForeground(new java.awt.Color(0, 0, 0));
        jRadioButton8.setText("Ar-cond.");
        jRadioButton8.setPreferredSize(new java.awt.Dimension(10, 20));
        jRadioButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton8ActionPerformed(evt);
            }
        });
        jPanel5.add(jRadioButton8);

        jRadioButton9.setForeground(new java.awt.Color(0, 0, 0));
        jRadioButton9.setText("Data-Show");
        jRadioButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton9ActionPerformed(evt);
            }
        });
        jPanel5.add(jRadioButton9);

        jRadioButton10.setForeground(new java.awt.Color(0, 0, 0));
        jRadioButton10.setText("Luzes");
        jPanel5.add(jRadioButton10);

        jButton4.setBackground(new java.awt.Color(153, 153, 153));
        jButton4.setForeground(new java.awt.Color(0, 0, 0));
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/delete.png"))); // NOI18N
        jButton4.setBorder(null);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabelhoraAtiv.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 14)); // NOI18N
        jLabelhoraAtiv.setForeground(new java.awt.Color(0, 0, 0));
        jLabelhoraAtiv.setText("horaAtiv:");

        jLabelhoraDesativ.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 14)); // NOI18N
        jLabelhoraDesativ.setForeground(new java.awt.Color(0, 0, 0));
        jLabelhoraDesativ.setText("horaDesativ:");

        jSeparator3.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jLabelhoraAtivEd.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 14)); // NOI18N
        jLabelhoraAtivEd.setForeground(new java.awt.Color(0, 0, 0));
        jLabelhoraAtivEd.setText("XXXXXXXXX");

        jLabelhoraDesativEd.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 14)); // NOI18N
        jLabelhoraDesativEd.setForeground(new java.awt.Color(0, 0, 0));
        jLabelhoraDesativEd.setText("XXXXXXXXX");

        jSeparator4.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator4.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jLabelSalas.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 14)); // NOI18N
        jLabelSalas.setForeground(new java.awt.Color(0, 0, 0));
        jLabelSalas.setText("Salas:");

        jLabelSalasEd.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 14)); // NOI18N
        jLabelSalasEd.setForeground(new java.awt.Color(0, 0, 0));
        jLabelSalasEd.setText("XXXXXXXXX");

        jSeparator5.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator5.setOrientation(javax.swing.SwingConstants.VERTICAL);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelTitulo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabelTituloEd))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelAutor)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelAutorEd)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelInicio)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelInicioEd))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jLabelFim)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelFimEd)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelhoraAtiv)
                    .addComponent(jLabelhoraDesativ))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelhoraDesativEd))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabelhoraAtivEd)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addComponent(jLabelSalas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelSalasEd)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addComponent(jButton4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonEditar)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addComponent(jSeparator2)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButtonEditar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabelAutor)
                                .addComponent(jLabelAutorEd)
                                .addComponent(jLabelInicioEd)
                                .addComponent(jLabelhoraAtiv)
                                .addComponent(jLabelhoraAtivEd)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabelFim)
                                .addComponent(jLabelFimEd)
                                .addComponent(jLabelhoraDesativ, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabelhoraDesativEd))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabelTitulo)
                                .addComponent(jLabelTituloEd))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabelSalas, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabelSalasEd))
                            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jRadioButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton9ActionPerformed

    private void jRadioButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton8ActionPerformed

    private void jButtonEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonEditarActionPerformed

    private void jRadioButtonSegundaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonSegundaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonSegundaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButtonEditar;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabelAutor;
    private javax.swing.JLabel jLabelAutorEd;
    private javax.swing.JLabel jLabelFim;
    private javax.swing.JLabel jLabelFimEd;
    private javax.swing.JLabel jLabelInicio;
    private javax.swing.JLabel jLabelInicioEd;
    private javax.swing.JLabel jLabelSalas;
    private javax.swing.JLabel jLabelSalasEd;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JLabel jLabelTituloEd;
    private javax.swing.JLabel jLabelhoraAtiv;
    private javax.swing.JLabel jLabelhoraAtivEd;
    private javax.swing.JLabel jLabelhoraDesativ;
    private javax.swing.JLabel jLabelhoraDesativEd;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JRadioButton jRadioButton10;
    private javax.swing.JRadioButton jRadioButton8;
    private javax.swing.JRadioButton jRadioButton9;
    private javax.swing.JRadioButton jRadioButtonDomingo;
    private javax.swing.JRadioButton jRadioButtonQuarta;
    private javax.swing.JRadioButton jRadioButtonQuinta;
    private javax.swing.JRadioButton jRadioButtonSabado;
    private javax.swing.JRadioButton jRadioButtonSegunda;
    private javax.swing.JRadioButton jRadioButtonSexta;
    private javax.swing.JRadioButton jRadioButtonTerca;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    // End of variables declaration//GEN-END:variables
}
