/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Aplicacao;


import Modelo.Agendamento;
import java.awt.Color;
import java.sql.Time;
import java.text.SimpleDateFormat;
import java.time.LocalTime;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Calendar;
import java.util.Collections;
import java.util.Date;
import java.util.List;
import java.util.stream.Collectors;
import javax.swing.JOptionPane;
import javax.swing.JRadioButton;


/**
 *
 * @author LENOVO
 */
public class AgendamentoPanel extends javax.swing.JPanel {
    private int idAgendamento;
    private Agendamento agen;

    public AgendamentoPanel(){
        initComponents();
    }
    /**
     * Creates new form AgendamentoPanel
     */
    public AgendamentoPanel(int idAgendamento, String autor, String titulo, Calendar dataIn, Calendar dataF, 
            Time hAtv, Time hDesat, int[] diaSemana, int[] salas, ArrayList<String> dispositivos) {
        initComponents();
        this.idAgendamento=idAgendamento;
        
        atualizar(autor, titulo, dataIn, dataF, hAtv, hDesat, diaSemana, salas, dispositivos);
        
    }

    public void setIdAgendamento(int idAgendamento) {
        this.idAgendamento = idAgendamento;
    }

    public int getIdAgendamento() {
        return idAgendamento;
    }
    
    public void atualizar(String autor, String titulo, Calendar dataIn, Calendar dataF, 
            Time hAtv, Time hDesat, int[] diaSemana, int[] salas, ArrayList<String> dispositivos){
        agen=new Agendamento(autor, titulo, dataIn, dataF, hAtv, hDesat, diaSemana, salas, dispositivos);
        agen.setIdAgendamento(this.idAgendamento);
        
        
        
        jLabelAutorEd.setText(autor);
        jLabelTituloEd.setText(titulo);
        
        SimpleDateFormat formatador = new SimpleDateFormat("dd/MM/yyyy");
        // 2. Converta o Calendar para Date (getTime())
        Date dateAtv = dataIn.getTime();
        Date dateDesat = dataF.getTime();
        // 3. Formate o objeto Date para String
        jLabelInicioEd.setText(formatador.format(dateAtv));
        jLabelFimEd.setText(formatador.format(dateDesat));
        
        List<JRadioButton> radioSemana = new ArrayList<>();
        JRadioButton[] radioSemanaArray={jRadioButtonDomingo,jRadioButtonSegunda, jRadioButtonTerca, jRadioButtonQuarta,
        jRadioButtonQuinta, jRadioButtonSexta, jRadioButtonSabado};
        Collections.addAll(radioSemana,radioSemanaArray );
        
       radioSemana.forEach(rb->rb.setSelected(false));
        for(int dia:diaSemana){
            int indice = dia-1;
            if(indice>=0 && indice<radioSemana.size()){
                radioSemana.get(indice).setSelected(true);
            }
        }
        
   
        String horaAtvFormatada =timeParaStringHHMM(hAtv);
        String horaDesatFormatada =timeParaStringHHMM(hDesat);
        jLabelhoraAtivEd.setText(horaAtvFormatada);
        jLabelhoraDesativEd.setText(horaDesatFormatada);
        
        jLabelSalasEd.setText(Arrays.stream(salas).boxed().map(Object::toString).collect(Collectors.joining(", ")));
        
        for(String dis:dispositivos){
            switch (dis) {
                case "AR":
                    jRadioButtonAR.setSelected(true);
                    break;
                case "LZ":
                    jRadioButtonLZ.setSelected(true);
                    break;
                case "DS":
                    jRadioButtonDS.setSelected(true);
                    break;
            }
        }
    }
    
    public String timeParaStringHHMM(Time horaSql) {
        if (horaSql == null) {
            return ""; // Ou lance uma exceção, dependendo da sua regra de negócio
        }

        // 1. Converter java.sql.Time para LocalTime
        LocalTime localTime = horaSql.toLocalTime();

        // 2. Definir o formato desejado (HH:mm)
        // 'HH' para hora em formato 24h, 'mm' para minuto.
        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("HH:mm");

        // 3. Formatar e retornar a String
        return localTime.format(formatter);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        jLabelAutor = new javax.swing.JLabel();
        jLabelInicio = new javax.swing.JLabel();
        jLabelFim = new javax.swing.JLabel();
        jButtonEditar = new javax.swing.JButton();
        jLabelTitulo = new javax.swing.JLabel();
        jLabelAutorEd = new javax.swing.JLabel();
        jLabelTituloEd = new javax.swing.JLabel();
        jLabelInicioEd = new javax.swing.JLabel();
        jLabelFimEd = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jPanel3 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jRadioButtonSegunda = new javax.swing.JRadioButton();
        jRadioButtonTerca = new javax.swing.JRadioButton();
        jRadioButtonQuarta = new javax.swing.JRadioButton();
        jRadioButtonQuinta = new javax.swing.JRadioButton();
        jRadioButtonSexta = new javax.swing.JRadioButton();
        jRadioButtonSabado = new javax.swing.JRadioButton();
        jRadioButtonDomingo = new javax.swing.JRadioButton();
        jPanel5 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jRadioButtonLZ = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jRadioButtonAR = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jRadioButtonDS = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jLabelhoraAtiv = new javax.swing.JLabel();
        jLabelhoraDesativ = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jLabelhoraAtivEd = new javax.swing.JLabel();
        jLabelhoraDesativEd = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jLabelSalas = new javax.swing.JLabel();
        jLabelSalasEd = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();

        setBackground(new java.awt.Color(153, 153, 153));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        setMaximumSize(new java.awt.Dimension(1600, 85));
        setMinimumSize(new java.awt.Dimension(1343, 85));
        setPreferredSize(new java.awt.Dimension(1343, 85));

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jLabelAutor.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 14)); // NOI18N
        jLabelAutor.setForeground(new java.awt.Color(0, 0, 0));
        jLabelAutor.setText("Autor:");

        jLabelInicio.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 14)); // NOI18N
        jLabelInicio.setForeground(new java.awt.Color(0, 0, 0));
        jLabelInicio.setText("Inicio:");

        jLabelFim.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 14)); // NOI18N
        jLabelFim.setForeground(new java.awt.Color(0, 0, 0));
        jLabelFim.setText("Fim:");

        jButtonEditar.setBackground(new java.awt.Color(153, 153, 153));
        jButtonEditar.setForeground(new java.awt.Color(0, 0, 0));
        jButtonEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/editar.png"))); // NOI18N
        jButtonEditar.setBorder(null);
        jButtonEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditarActionPerformed(evt);
            }
        });

        jLabelTitulo.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 14)); // NOI18N
        jLabelTitulo.setForeground(new java.awt.Color(0, 0, 0));
        jLabelTitulo.setText("Titulo:");

        jLabelAutorEd.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 14)); // NOI18N
        jLabelAutorEd.setForeground(new java.awt.Color(0, 0, 0));
        jLabelAutorEd.setText("XXXXXXXXX");

        jLabelTituloEd.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 14)); // NOI18N
        jLabelTituloEd.setForeground(new java.awt.Color(0, 0, 0));
        jLabelTituloEd.setText("XXXXXXXXX");

        jLabelInicioEd.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 14)); // NOI18N
        jLabelInicioEd.setForeground(new java.awt.Color(0, 0, 0));
        jLabelInicioEd.setText("XXXXXXXXX");

        jLabelFimEd.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 14)); // NOI18N
        jLabelFimEd.setForeground(new java.awt.Color(0, 0, 0));
        jLabelFimEd.setText("XXXXXXXXX");

        jSeparator2.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jPanel3.setBackground(new java.awt.Color(153, 153, 153));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel3.setPreferredSize(new java.awt.Dimension(50, 50));
        jPanel3.setLayout(new java.awt.GridLayout(2, 1));

        jLabel6.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText(" S    T   Q   Q   S   S   D");
        jPanel3.add(jLabel6);

        jPanel4.setBackground(new java.awt.Color(153, 153, 153));
        jPanel4.setPreferredSize(new java.awt.Dimension(50, 25));
        jPanel4.setLayout(new java.awt.GridLayout(1, 7, 5, 0));

        jRadioButtonSegunda.setEnabled(false);
        jRadioButtonSegunda.setPreferredSize(new java.awt.Dimension(10, 20));
        jRadioButtonSegunda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonSegundaActionPerformed(evt);
            }
        });
        jPanel4.add(jRadioButtonSegunda);

        jRadioButtonTerca.setEnabled(false);
        jPanel4.add(jRadioButtonTerca);

        jRadioButtonQuarta.setEnabled(false);
        jPanel4.add(jRadioButtonQuarta);

        jRadioButtonQuinta.setEnabled(false);
        jPanel4.add(jRadioButtonQuinta);

        jRadioButtonSexta.setEnabled(false);
        jPanel4.add(jRadioButtonSexta);

        jRadioButtonSabado.setEnabled(false);
        jPanel4.add(jRadioButtonSabado);

        jRadioButtonDomingo.setEnabled(false);
        jPanel4.add(jRadioButtonDomingo);

        jPanel3.add(jPanel4);

        jPanel5.setBackground(new java.awt.Color(153, 153, 153));
        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel5.setMinimumSize(new java.awt.Dimension(70, 50));
        jPanel5.setPreferredSize(new java.awt.Dimension(25, 25));
        jPanel5.setLayout(new java.awt.GridLayout(2, 2));

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));
        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.LINE_AXIS));

        jRadioButtonLZ.setForeground(new java.awt.Color(0, 0, 0));
        jRadioButtonLZ.setEnabled(false);
        jRadioButtonLZ.setMargin(new java.awt.Insets(2, 1, 3, 2));
        jRadioButtonLZ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonLZActionPerformed(evt);
            }
        });
        jPanel1.add(jRadioButtonLZ);

        jLabel1.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Luzes");
        jPanel1.add(jLabel1);

        jPanel5.add(jPanel1);

        jPanel6.setBackground(new java.awt.Color(153, 153, 153));
        jPanel6.setLayout(new javax.swing.BoxLayout(jPanel6, javax.swing.BoxLayout.LINE_AXIS));

        jRadioButtonAR.setForeground(new java.awt.Color(0, 0, 0));
        jRadioButtonAR.setEnabled(false);
        jRadioButtonAR.setMargin(new java.awt.Insets(2, 1, 3, 2));
        jRadioButtonAR.setPreferredSize(new java.awt.Dimension(10, 20));
        jRadioButtonAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonARActionPerformed(evt);
            }
        });
        jPanel6.add(jRadioButtonAR);

        jLabel2.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Ar-condionado");
        jPanel6.add(jLabel2);

        jPanel5.add(jPanel6);

        jPanel2.setBackground(new java.awt.Color(153, 153, 153));
        jPanel2.setLayout(new javax.swing.BoxLayout(jPanel2, javax.swing.BoxLayout.LINE_AXIS));

        jRadioButtonDS.setForeground(new java.awt.Color(204, 204, 204));
        jRadioButtonDS.setEnabled(false);
        jRadioButtonDS.setMargin(new java.awt.Insets(2, 1, 3, 2));
        jRadioButtonDS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonDSActionPerformed(evt);
            }
        });
        jPanel2.add(jRadioButtonDS);

        jLabel3.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("DataShow");
        jPanel2.add(jLabel3);

        jPanel5.add(jPanel2);

        jButton4.setBackground(new java.awt.Color(153, 153, 153));
        jButton4.setForeground(new java.awt.Color(0, 0, 0));
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/delete.png"))); // NOI18N
        jButton4.setBorder(null);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabelhoraAtiv.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 14)); // NOI18N
        jLabelhoraAtiv.setForeground(new java.awt.Color(0, 0, 0));
        jLabelhoraAtiv.setText("horaAtiv:");

        jLabelhoraDesativ.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 14)); // NOI18N
        jLabelhoraDesativ.setForeground(new java.awt.Color(0, 0, 0));
        jLabelhoraDesativ.setText("horaDesativ:");

        jSeparator3.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jLabelhoraAtivEd.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 14)); // NOI18N
        jLabelhoraAtivEd.setForeground(new java.awt.Color(0, 0, 0));
        jLabelhoraAtivEd.setText("XXXXXXXXX");

        jLabelhoraDesativEd.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 14)); // NOI18N
        jLabelhoraDesativEd.setForeground(new java.awt.Color(0, 0, 0));
        jLabelhoraDesativEd.setText("XXXXXXXXX");

        jSeparator4.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator4.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jLabelSalas.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 14)); // NOI18N
        jLabelSalas.setForeground(new java.awt.Color(0, 0, 0));
        jLabelSalas.setText("Salas:");

        jLabelSalasEd.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 14)); // NOI18N
        jLabelSalasEd.setForeground(new java.awt.Color(0, 0, 0));
        jLabelSalasEd.setText("XXXXXXXXX");

        jSeparator5.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator5.setOrientation(javax.swing.SwingConstants.VERTICAL);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelTitulo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabelTituloEd))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelAutor)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelAutorEd)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelInicio)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelInicioEd))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jLabelFim)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelFimEd)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelhoraAtiv)
                    .addComponent(jLabelhoraDesativ))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelhoraDesativEd))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabelhoraAtivEd)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addComponent(jLabelSalas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelSalasEd)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 179, Short.MAX_VALUE)
                .addComponent(jButton4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonEditar)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addComponent(jSeparator2)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButtonEditar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabelAutor)
                                .addComponent(jLabelAutorEd)
                                .addComponent(jLabelInicioEd)
                                .addComponent(jLabelhoraAtiv)
                                .addComponent(jLabelhoraAtivEd)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabelFim)
                                .addComponent(jLabelFimEd)
                                .addComponent(jLabelhoraDesativ, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabelhoraDesativEd))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabelTitulo)
                                .addComponent(jLabelTituloEd))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabelSalas, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabelSalasEd))
                            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        int resultado = JOptionPane.showConfirmDialog(
            null, // Componente pai (null para centralizar na tela)
            "Você tem certeza que deseja apagar o seguinte item?", // Mensagem
            "Confirmação de Exclusão", // Título da Janela
            JOptionPane.OK_CANCEL_OPTION, // Opções de Botão: OK e Cancel
            JOptionPane.WARNING_MESSAGE // Tipo de Mensagem (Geralmente um aviso)
        );
        if(resultado==JOptionPane.OK_OPTION){
        String resp=MainApp.sessao.trataAcao("--deletAgendamento--"+Integer.toString(idAgendamento));
        if(resp.contains("SUCESSO")){
            JOptionPane.showMessageDialog(null, "Agendamento eliminado com sucesso", "Sucesso", JOptionPane.INFORMATION_MESSAGE);
        }else{
            JOptionPane.showMessageDialog(null, "Erro ao eliminar", "Erro", JOptionPane.ERROR_MESSAGE);
        }
        }
        
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButtonEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditarActionPerformed
        // TODO add your handling code here:
        EditarAgendamento edit= new EditarAgendamento(agen);
    }//GEN-LAST:event_jButtonEditarActionPerformed

    private void jRadioButtonSegundaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonSegundaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonSegundaActionPerformed

    private void jRadioButtonARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonARActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonARActionPerformed

    private void jRadioButtonDSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonDSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonDSActionPerformed

    private void jRadioButtonLZActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonLZActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonLZActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButtonEditar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabelAutor;
    private javax.swing.JLabel jLabelAutorEd;
    private javax.swing.JLabel jLabelFim;
    private javax.swing.JLabel jLabelFimEd;
    private javax.swing.JLabel jLabelInicio;
    private javax.swing.JLabel jLabelInicioEd;
    private javax.swing.JLabel jLabelSalas;
    private javax.swing.JLabel jLabelSalasEd;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JLabel jLabelTituloEd;
    private javax.swing.JLabel jLabelhoraAtiv;
    private javax.swing.JLabel jLabelhoraAtivEd;
    private javax.swing.JLabel jLabelhoraDesativ;
    private javax.swing.JLabel jLabelhoraDesativEd;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JRadioButton jRadioButtonAR;
    private javax.swing.JRadioButton jRadioButtonDS;
    private javax.swing.JRadioButton jRadioButtonDomingo;
    private javax.swing.JRadioButton jRadioButtonLZ;
    private javax.swing.JRadioButton jRadioButtonQuarta;
    private javax.swing.JRadioButton jRadioButtonQuinta;
    private javax.swing.JRadioButton jRadioButtonSabado;
    private javax.swing.JRadioButton jRadioButtonSegunda;
    private javax.swing.JRadioButton jRadioButtonSexta;
    private javax.swing.JRadioButton jRadioButtonTerca;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    // End of variables declaration//GEN-END:variables
}
