/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Aplicacao;

import Modelo.Dispositivo;
import java.util.Arrays;
import java.util.stream.Collectors;
import javax.swing.JOptionPane;

/**
 *
 * @author LENOVO
 */
public class DispositivosPanel extends javax.swing.JPanel {
    private int id;
    private Dispositivo dis;
    /**
     * Creates new form AgendamentoPanel
     */
    public DispositivosPanel() {
        initComponents();
    }
    
    public DispositivosPanel(Dispositivo dis) {
        initComponents();
        this.id=dis.getId();
        atualizar(dis);
        this.dis=dis;
    }
    
    public void atualizar(Dispositivo dis){
        jLabelMarcaEd.setText(dis.getMarca());
        jLabelModeloEd.setText(dis.getModelo());
        int num=dis.getListaCodigos().size();
        if(dis.getTipo().contains("AR")){
            jLabelTipoEd.setText("Ar-condicionado");
            if(num==30){
                jRadioButtonCompleto.setSelected(true);
            }else if(num<30 && num>0 ){
                jRadioButtonIncompleto.setSelected(true);
            }else{
                jRadioButtonEditCod.setSelected(true);
            }
        }else{
            jLabelTipoEd.setText("DataShow");
            if(num==10){
                jRadioButtonCompleto.setSelected(true);
            }else if(num<10 && num>0 ){
                jRadioButtonIncompleto.setSelected(true);
            }else{
                jRadioButtonEditCod.setSelected(true);
            }
        }
        jLabelSalasREd.setText(Arrays.stream(dis.getSalasRelacionadas()).boxed().map(Object::toString).collect(Collectors.joining(", ")));
        this.dis=dis;
    }

    public void setId(int id) {
        this.id = id;
    }

    public int getId() {
        return id;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabelMarca = new javax.swing.JLabel();
        jLabelTipo = new javax.swing.JLabel();
        jLabelSalasR = new javax.swing.JLabel();
        jButtonEditar = new javax.swing.JButton();
        jLabelTitulo = new javax.swing.JLabel();
        jLabelMarcaEd = new javax.swing.JLabel();
        jLabelModeloEd = new javax.swing.JLabel();
        jLabelTipoEd = new javax.swing.JLabel();
        jLabelSalasREd = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jButton4 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jRadioButtonCompleto = new javax.swing.JRadioButton();
        jRadioButtonIncompleto = new javax.swing.JRadioButton();
        jRadioButtonEditCod = new javax.swing.JRadioButton();

        jPanel2.setBackground(new java.awt.Color(153, 153, 153));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel2.setMaximumSize(new java.awt.Dimension(32767, 70));
        jPanel2.setName(""); // NOI18N
        jPanel2.setPreferredSize(new java.awt.Dimension(800, 120));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 803, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 76, Short.MAX_VALUE)
        );

        setBackground(new java.awt.Color(153, 153, 153));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        setMaximumSize(new java.awt.Dimension(1600, 85));
        setMinimumSize(new java.awt.Dimension(1343, 85));
        setPreferredSize(new java.awt.Dimension(1343, 85));

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jLabelMarca.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 14)); // NOI18N
        jLabelMarca.setForeground(new java.awt.Color(0, 0, 0));
        jLabelMarca.setText("Marca:");

        jLabelTipo.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 14)); // NOI18N
        jLabelTipo.setForeground(new java.awt.Color(0, 0, 0));
        jLabelTipo.setText("Tipo:");

        jLabelSalasR.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 14)); // NOI18N
        jLabelSalasR.setForeground(new java.awt.Color(0, 0, 0));
        jLabelSalasR.setText("Salas relacionadas:");

        jButtonEditar.setBackground(new java.awt.Color(153, 153, 153));
        jButtonEditar.setForeground(new java.awt.Color(0, 0, 0));
        jButtonEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/editar.png"))); // NOI18N
        jButtonEditar.setBorder(null);
        jButtonEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditarActionPerformed(evt);
            }
        });

        jLabelTitulo.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 14)); // NOI18N
        jLabelTitulo.setForeground(new java.awt.Color(0, 0, 0));
        jLabelTitulo.setText("Modelo:");

        jLabelMarcaEd.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 14)); // NOI18N
        jLabelMarcaEd.setForeground(new java.awt.Color(0, 0, 0));
        jLabelMarcaEd.setText("XXXXXXXXX");

        jLabelModeloEd.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 14)); // NOI18N
        jLabelModeloEd.setForeground(new java.awt.Color(0, 0, 0));
        jLabelModeloEd.setText("XXXXXXXXX");

        jLabelTipoEd.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 14)); // NOI18N
        jLabelTipoEd.setForeground(new java.awt.Color(0, 0, 0));
        jLabelTipoEd.setText("XXXXXXXXX");

        jLabelSalasREd.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 14)); // NOI18N
        jLabelSalasREd.setForeground(new java.awt.Color(0, 0, 0));
        jLabelSalasREd.setText("XXXXXXXXX");

        jSeparator2.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jButton4.setBackground(new java.awt.Color(153, 153, 153));
        jButton4.setForeground(new java.awt.Color(0, 0, 0));
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/delete.png"))); // NOI18N
        jButton4.setBorder(null);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jPanel5.setBackground(new java.awt.Color(153, 153, 153));
        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel5.setMinimumSize(new java.awt.Dimension(70, 50));
        jPanel5.setPreferredSize(new java.awt.Dimension(25, 25));
        jPanel5.setLayout(new java.awt.GridLayout(1, 5));

        jLabel6.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Códigos:");
        jPanel5.add(jLabel6);

        jRadioButtonCompleto.setForeground(new java.awt.Color(0, 0, 0));
        jRadioButtonCompleto.setText("Completo");
        jRadioButtonCompleto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonCompletoActionPerformed(evt);
            }
        });
        jPanel5.add(jRadioButtonCompleto);

        jRadioButtonIncompleto.setForeground(new java.awt.Color(0, 0, 0));
        jRadioButtonIncompleto.setText("Incompleto");
        jRadioButtonIncompleto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonIncompletoActionPerformed(evt);
            }
        });
        jPanel5.add(jRadioButtonIncompleto);

        jRadioButtonEditCod.setForeground(new java.awt.Color(0, 0, 0));
        jRadioButtonEditCod.setText("Sem codigos");
        jRadioButtonEditCod.setPreferredSize(new java.awt.Dimension(10, 20));
        jRadioButtonEditCod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonEditCodActionPerformed(evt);
            }
        });
        jPanel5.add(jRadioButtonEditCod);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelTitulo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelModeloEd))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabelMarca)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelMarcaEd)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelTipo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelTipoEd))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelSalasR)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelSalasREd)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 377, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 455, Short.MAX_VALUE)
                .addComponent(jButton4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonEditar)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addComponent(jSeparator2)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabelMarca)
                                .addComponent(jLabelMarcaEd)
                                .addComponent(jLabelTipoEd)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabelSalasR)
                                .addComponent(jLabelSalasREd))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabelTitulo)
                                .addComponent(jLabelModeloEd))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButtonEditar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(19, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        int resultado = JOptionPane.showConfirmDialog(
            null, // Componente pai (null para centralizar na tela)
            "Você tem certeza que deseja apagar o seguinte item?", // Mensagem
            "Confirmação de Exclusão", // Título da Janela
            JOptionPane.OK_CANCEL_OPTION, // Opções de Botão: OK e Cancel
            JOptionPane.WARNING_MESSAGE // Tipo de Mensagem (Geralmente um aviso)
        );
        if(resultado==JOptionPane.OK_OPTION){
        String resp=MainApp.sessao.trataAcao("--deletDispositivo--"+Integer.toString(id));
        if(resp.contains("SUCESSO")){
            JOptionPane.showMessageDialog(null, "Dispositivo eliminado com sucesso", "Sucesso", JOptionPane.INFORMATION_MESSAGE);
        }else{
            JOptionPane.showMessageDialog(null, "Erro ao eliminar", "Erro", JOptionPane.ERROR_MESSAGE);
        }
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButtonEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditarActionPerformed
        // TODO add your handling code here:
        EditarDispositivo edit= new EditarDispositivo(dis);
        edit.setVisible(true);
    }//GEN-LAST:event_jButtonEditarActionPerformed

    private void jRadioButtonCompletoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonCompletoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonCompletoActionPerformed

    private void jRadioButtonIncompletoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonIncompletoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonIncompletoActionPerformed

    private void jRadioButtonEditCodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonEditCodActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonEditCodActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButtonEditar;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabelMarca;
    private javax.swing.JLabel jLabelMarcaEd;
    private javax.swing.JLabel jLabelModeloEd;
    private javax.swing.JLabel jLabelSalasR;
    private javax.swing.JLabel jLabelSalasREd;
    private javax.swing.JLabel jLabelTipo;
    private javax.swing.JLabel jLabelTipoEd;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JRadioButton jRadioButtonCompleto;
    private javax.swing.JRadioButton jRadioButtonEditCod;
    private javax.swing.JRadioButton jRadioButtonIncompleto;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    // End of variables declaration//GEN-END:variables
}
