/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Aplicacao;

import java.util.Collections;
import java.util.Comparator;
import javax.swing.SwingUtilities;

/**
 *
 * @author LENOVO
 */
public class FrameSala extends javax.swing.JFrame {
    private int nsala;
    private FrameSala sala;
    /**
     * Creates new form Sala
     */
    
    public FrameSala(){
        initComponents();
        setVisible(true);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelPrincipal = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabelIfamLogo = new javax.swing.JLabel();
        jLabelTemperatura = new javax.swing.JLabel();
        jLabelHumidade = new javax.swing.JLabel();
        jLabelPresença = new javax.swing.JLabel();
        jLabelAr = new javax.swing.JLabel();
        jLabelLuz = new javax.swing.JLabel();
        jLabelDS1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabelSala = new javax.swing.JLabel();
        jLabelTemperaturaValor = new javax.swing.JLabel();
        jLabelHumidadeValor = new javax.swing.JLabel();
        jLabelHumidadeValor1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jButtonEnviar = new javax.swing.JButton();
        comboBoxTemperatura = new javax.swing.JComboBox<>();
        jLabelTemperatura1 = new javax.swing.JLabel();
        jLabelTemperatura2 = new javax.swing.JLabel();
        jLabelModo = new javax.swing.JLabel();
        comboBoxModo = new javax.swing.JComboBox<>();
        jLabelDS2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridLayout(1, 0));

        jPanelPrincipal.setBackground(new java.awt.Color(0, 51, 102));
        jPanelPrincipal.setPreferredSize(new java.awt.Dimension(800, 570));
        jPanelPrincipal.setLayout(new java.awt.GridLayout(1, 3));

        jPanel1.setBackground(new java.awt.Color(0, 51, 102));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        jLabelIfamLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/IFAM_logo.png"))); // NOI18N
        jLabelIfamLogo.setText("jLabel1");

        jLabelTemperatura.setBackground(new java.awt.Color(255, 255, 255));
        jLabelTemperatura.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 18)); // NOI18N
        jLabelTemperatura.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTemperatura.setText("Temperatura:");
        jLabelTemperatura.setToolTipText("");

        jLabelHumidade.setBackground(new java.awt.Color(255, 255, 255));
        jLabelHumidade.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 18)); // NOI18N
        jLabelHumidade.setForeground(new java.awt.Color(255, 255, 255));
        jLabelHumidade.setText("Umidade:");
        jLabelHumidade.setToolTipText("");

        jLabelPresença.setBackground(new java.awt.Color(255, 255, 255));
        jLabelPresença.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 18)); // NOI18N
        jLabelPresença.setForeground(new java.awt.Color(255, 255, 255));
        jLabelPresença.setText("Presença:");
        jLabelPresença.setToolTipText("");

        jLabelAr.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/ar-condicionado-on (1).png"))); // NOI18N
        jLabelAr.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelArMouseClicked(evt);
            }
        });

        jLabelLuz.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/luz-on (1).png"))); // NOI18N

        jLabelDS1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/data-show-on (1).png"))); // NOI18N
        jLabelDS1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelDS1MouseClicked(evt);
            }
        });

        jPanel4.setBackground(new java.awt.Color(51, 51, 51));
        jPanel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabelSala.setBackground(new java.awt.Color(255, 255, 255));
        jLabelSala.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 36)); // NOI18N
        jLabelSala.setForeground(new java.awt.Color(255, 255, 255));
        jLabelSala.setText("Sala");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabelSala, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelSala, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        jLabelTemperaturaValor.setBackground(new java.awt.Color(255, 255, 255));
        jLabelTemperaturaValor.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 18)); // NOI18N
        jLabelTemperaturaValor.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTemperaturaValor.setText("XX");
        jLabelTemperaturaValor.setToolTipText("");

        jLabelHumidadeValor.setBackground(new java.awt.Color(255, 255, 255));
        jLabelHumidadeValor.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 18)); // NOI18N
        jLabelHumidadeValor.setForeground(new java.awt.Color(255, 255, 255));
        jLabelHumidadeValor.setText("XX");
        jLabelHumidadeValor.setToolTipText("");

        jLabelHumidadeValor1.setBackground(new java.awt.Color(255, 255, 255));
        jLabelHumidadeValor1.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 18)); // NOI18N
        jLabelHumidadeValor1.setForeground(new java.awt.Color(255, 255, 255));
        jLabelHumidadeValor1.setText("XX");
        jLabelHumidadeValor1.setToolTipText("");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelIfamLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabelAr)
                                .addGap(43, 43, 43)
                                .addComponent(jLabelLuz)
                                .addGap(43, 43, 43)
                                .addComponent(jLabelDS1))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabelHumidade)
                                    .addGap(18, 18, 18)
                                    .addComponent(jLabelHumidadeValor))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabelTemperatura)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jLabelTemperaturaValor))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                    .addGap(70, 70, 70)
                                    .addComponent(jLabelPresença)
                                    .addGap(18, 18, 18)
                                    .addComponent(jLabelHumidadeValor1))))))
                .addGap(20, 54, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelTemperatura)
                    .addComponent(jLabelTemperaturaValor))
                .addGap(50, 50, 50)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelHumidade)
                            .addComponent(jLabelHumidadeValor))
                        .addGap(50, 50, 50)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelPresença)
                            .addComponent(jLabelHumidadeValor1))
                        .addGap(84, 84, 84)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabelAr)
                            .addComponent(jLabelLuz)))
                    .addComponent(jLabelDS1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                .addComponent(jLabelIfamLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanelPrincipal.add(jPanel1);

        jPanel2.setBackground(new java.awt.Color(0, 51, 102));
        jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));

        jButtonEnviar.setBackground(new java.awt.Color(204, 204, 204));
        jButtonEnviar.setForeground(new java.awt.Color(0, 0, 0));
        jButtonEnviar.setText("Enviar");
        jButtonEnviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEnviarActionPerformed(evt);
            }
        });

        comboBoxTemperatura.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 14)); // NOI18N
        comboBoxTemperatura.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "16", "17", "18", "19", "20", "21", "22", "23", "24", "25" }));
        comboBoxTemperatura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxTemperaturaActionPerformed(evt);
            }
        });

        jLabelTemperatura1.setBackground(new java.awt.Color(255, 255, 255));
        jLabelTemperatura1.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 24)); // NOI18N
        jLabelTemperatura1.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTemperatura1.setText("Ar-condicionado");
        jLabelTemperatura1.setToolTipText("");

        jLabelTemperatura2.setBackground(new java.awt.Color(255, 255, 255));
        jLabelTemperatura2.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 18)); // NOI18N
        jLabelTemperatura2.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTemperatura2.setText("Temperatura:");
        jLabelTemperatura2.setToolTipText("");

        jLabelModo.setBackground(new java.awt.Color(255, 255, 255));
        jLabelModo.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 18)); // NOI18N
        jLabelModo.setForeground(new java.awt.Color(255, 255, 255));
        jLabelModo.setText("Modo:");
        jLabelModo.setToolTipText("");

        comboBoxModo.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 14)); // NOI18N
        comboBoxModo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cool", "Fan", "Auto", "Dry" }));
        comboBoxModo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxModoActionPerformed(evt);
            }
        });

        jLabelDS2.setBackground(new java.awt.Color(255, 255, 255));
        jLabelDS2.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 24)); // NOI18N
        jLabelDS2.setForeground(new java.awt.Color(255, 255, 255));
        jLabelDS2.setText("Data-show");
        jLabelDS2.setToolTipText("");

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/dataShow/para-baixo.PNG"))); // NOI18N

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/dataShow/ok.PNG"))); // NOI18N

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/dataShow/para-cima.PNG"))); // NOI18N

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/dataShow/direita.PNG"))); // NOI18N

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/dataShow/esquerda.PNG"))); // NOI18N

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/dataShow/esc.PNG"))); // NOI18N

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/dataShow/freeze.PNG"))); // NOI18N

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/dataShow/menu.PNG"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(177, 177, 177)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelTemperatura1)
                            .addComponent(jLabelDS2)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jLabel6)
                        .addGap(83, 83, 83)
                        .addComponent(jLabel1))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(176, 176, 176)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel9)
                .addGap(34, 34, 34))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(115, 115, 115)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(47, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabelModo)
                            .addComponent(jLabelTemperatura2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(comboBoxTemperatura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(comboBoxModo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(170, 170, 170))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jButtonEnviar, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(188, 188, 188))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabelTemperatura1)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboBoxTemperatura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelTemperatura2))
                .addGap(33, 33, 33)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelModo)
                    .addComponent(comboBoxModo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButtonEnviar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelDS2)
                .addGap(14, 14, 14)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(19, 19, 19)))
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 71, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel9)
                    .addComponent(jLabel6))
                .addGap(16, 16, 16))
        );

        jPanelPrincipal.add(jPanel2);

        getContentPane().add(jPanelPrincipal);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void comboBoxTemperaturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxTemperaturaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboBoxTemperaturaActionPerformed

    private void comboBoxModoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxModoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboBoxModoActionPerformed

    private void jButtonEnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEnviarActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jButtonEnviarActionPerformed

    private void jLabelArMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelArMouseClicked
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_jLabelArMouseClicked

    private void jLabelDS1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelDS1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabelDS1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameSala.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameSala.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameSala.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameSala.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameSala().setVisible(true);
            }
        });
    }
     private class AtualizaDadosSala implements Runnable {

        @Override
        public void run() {
            while (isDisplayable()) {
                MainApp.sessao.salas();
                String resposta = MainApp.sessao.verificarResposta();
                
                
        
                try {
                    Thread.sleep(1000);
                } catch (InterruptedException ex) {
                    System.out.println("Erro ao atualizar");
                }

            }
            System.exit(0);
            MainApp.sessao.trataAcao("HD", nsala);
        }
       
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> comboBoxModo;
    private javax.swing.JComboBox<String> comboBoxTemperatura;
    private javax.swing.JButton jButtonEnviar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelAr;
    private javax.swing.JLabel jLabelDS1;
    private javax.swing.JLabel jLabelDS2;
    private javax.swing.JLabel jLabelHumidade;
    private javax.swing.JLabel jLabelHumidadeValor;
    private javax.swing.JLabel jLabelHumidadeValor1;
    private javax.swing.JLabel jLabelIfamLogo;
    private javax.swing.JLabel jLabelLuz;
    private javax.swing.JLabel jLabelModo;
    private javax.swing.JLabel jLabelPresença;
    private javax.swing.JLabel jLabelSala;
    private javax.swing.JLabel jLabelTemperatura;
    private javax.swing.JLabel jLabelTemperatura1;
    private javax.swing.JLabel jLabelTemperatura2;
    private javax.swing.JLabel jLabelTemperaturaValor;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanelPrincipal;
    // End of variables declaration//GEN-END:variables
}

