
   /*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Aplicacao;

import Modelo.Sala;
import com.google.gson.Gson;
import com.google.gson.reflect.TypeToken;
import java.util.Collections;
import java.util.Comparator;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.SwingUtilities;

/**
 *
 * @author LENOVO
 */
public class FrameSala extends javax.swing.JFrame {

    private Sala sala;
    private int nsala;
    private boolean estadoAr, estadoDS, estadoLuzes;
    private Gson gs;
    private java.lang.reflect.Type tipoSala;

    /**
     * Creates new form Sala
     */
    public FrameSala(int nsala) {
        initComponents();
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        setVisible(true);
        this.nsala = nsala;
        
        MainApp.sessao.trataAcao("OCP", nsala);
        gs = new Gson();
        this.tipoSala = new TypeToken<Sala>() {
        }.getType();
        String resposta = MainApp.sessao.getSala(nsala);
        sala = gs.fromJson(resposta, tipoSala);
        estadoAr = sala.isEstadoAr();
        estadoDS = sala.isEstadoDataShow();
        estadoLuzes = sala.isEstadoLuzes();
        if (!estadoAr) {
            jLabelAr.setIcon(new ImageIcon(getClass().getResource("/Imagens/ar-condicionado-off (1).png")));
        } else {

            jLabelAr.setIcon(new ImageIcon(getClass().getResource("/Imagens/ar-condicionado-on (1).png")));
        }
        if (!estadoLuzes) {
            jLabelLuz.setIcon(new ImageIcon(getClass().getResource("/Imagens/luz-off (1).png")));
        } else {
            jLabelLuz.setIcon(new ImageIcon(getClass().getResource("/Imagens/luz-on (1).png")));
        }
        if (!estadoDS) {

            jLabelDS.setIcon(new ImageIcon(getClass().getResource("/Imagens/data-show-off (1).png")));
        } else {

            jLabelDS.setIcon(new ImageIcon(getClass().getResource("/Imagens/data-show-on (1).png")));
        }
        new Thread(new AtualizaDadosSala()).start();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelPrincipal = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabelIfamLogo = new javax.swing.JLabel();
        jLabelTemperatura = new javax.swing.JLabel();
        jLabelHumidade = new javax.swing.JLabel();
        jLabelPresença = new javax.swing.JLabel();
        jLabelAr = new javax.swing.JLabel();
        jLabelLuz = new javax.swing.JLabel();
        jLabelDS = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabelSala = new javax.swing.JLabel();
        jLabelTemperaturaValor = new javax.swing.JLabel();
        jLabelHumidadeValor = new javax.swing.JLabel();
        jLabelPresencaValor = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jButtonEnviar = new javax.swing.JButton();
        comboBoxTemperatura = new javax.swing.JComboBox<>();
        jLabelTemperatura1 = new javax.swing.JLabel();
        jLabelTemperatura2 = new javax.swing.JLabel();
        jLabelModo = new javax.swing.JLabel();
        comboBoxModo = new javax.swing.JComboBox<>();
        jLabelDS2 = new javax.swing.JLabel();
        jLabelBaixo = new javax.swing.JLabel();
        jLabelOkey = new javax.swing.JLabel();
        jLabelCima = new javax.swing.JLabel();
        jLabelDireita = new javax.swing.JLabel();
        jLabelEsquerda = new javax.swing.JLabel();
        jLabelEsc = new javax.swing.JLabel();
        jLabelFreeze = new javax.swing.JLabel();
        jLabelMenu = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridLayout(1, 0));

        jPanelPrincipal.setBackground(new java.awt.Color(0, 51, 102));
        jPanelPrincipal.setPreferredSize(new java.awt.Dimension(800, 570));
        jPanelPrincipal.setLayout(new java.awt.GridLayout(1, 3));

        jPanel1.setBackground(new java.awt.Color(0, 51, 102));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        jLabelIfamLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/IFAM_logo.png"))); // NOI18N
        jLabelIfamLogo.setText("jLabel1");

        jLabelTemperatura.setBackground(new java.awt.Color(255, 255, 255));
        jLabelTemperatura.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 18)); // NOI18N
        jLabelTemperatura.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTemperatura.setText("Temperatura:");
        jLabelTemperatura.setToolTipText("");

        jLabelHumidade.setBackground(new java.awt.Color(255, 255, 255));
        jLabelHumidade.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 18)); // NOI18N
        jLabelHumidade.setForeground(new java.awt.Color(255, 255, 255));
        jLabelHumidade.setText("Umidade:");
        jLabelHumidade.setToolTipText("");

        jLabelPresença.setBackground(new java.awt.Color(255, 255, 255));
        jLabelPresença.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 18)); // NOI18N
        jLabelPresença.setForeground(new java.awt.Color(255, 255, 255));
        jLabelPresença.setText("Presença:");
        jLabelPresença.setToolTipText("");

        jLabelAr.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/ar-condicionado-on (1).png"))); // NOI18N
        jLabelAr.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelArMouseClicked(evt);
            }
        });

        jLabelLuz.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/luz-on (1).png"))); // NOI18N
        jLabelLuz.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelLuzMouseClicked(evt);
            }
        });

        jLabelDS.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/data-show-on (1).png"))); // NOI18N
        jLabelDS.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelDSMouseClicked(evt);
            }
        });

        jPanel4.setBackground(new java.awt.Color(51, 51, 51));
        jPanel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabelSala.setBackground(new java.awt.Color(255, 255, 255));
        jLabelSala.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 36)); // NOI18N
        jLabelSala.setForeground(new java.awt.Color(255, 255, 255));
        jLabelSala.setText("Sala");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabelSala, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelSala, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        jLabelTemperaturaValor.setBackground(new java.awt.Color(255, 255, 255));
        jLabelTemperaturaValor.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 18)); // NOI18N
        jLabelTemperaturaValor.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTemperaturaValor.setText("XX");
        jLabelTemperaturaValor.setToolTipText("");

        jLabelHumidadeValor.setBackground(new java.awt.Color(255, 255, 255));
        jLabelHumidadeValor.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 18)); // NOI18N
        jLabelHumidadeValor.setForeground(new java.awt.Color(255, 255, 255));
        jLabelHumidadeValor.setText("XX");
        jLabelHumidadeValor.setToolTipText("");

        jLabelPresencaValor.setBackground(new java.awt.Color(255, 255, 255));
        jLabelPresencaValor.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 18)); // NOI18N
        jLabelPresencaValor.setForeground(new java.awt.Color(255, 255, 255));
        jLabelPresencaValor.setText("XX");
        jLabelPresencaValor.setToolTipText("");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelIfamLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabelAr)
                                .addGap(43, 43, 43)
                                .addComponent(jLabelLuz)
                                .addGap(43, 43, 43)
                                .addComponent(jLabelDS))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabelHumidade)
                                    .addGap(18, 18, 18)
                                    .addComponent(jLabelHumidadeValor))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabelTemperatura)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jLabelTemperaturaValor))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                    .addGap(70, 70, 70)
                                    .addComponent(jLabelPresença)
                                    .addGap(18, 18, 18)
                                    .addComponent(jLabelPresencaValor))))))
                .addGap(20, 54, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelTemperatura)
                    .addComponent(jLabelTemperaturaValor))
                .addGap(50, 50, 50)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelHumidade)
                            .addComponent(jLabelHumidadeValor))
                        .addGap(50, 50, 50)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelPresença)
                            .addComponent(jLabelPresencaValor))
                        .addGap(84, 84, 84)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabelAr)
                            .addComponent(jLabelLuz)))
                    .addComponent(jLabelDS))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                .addComponent(jLabelIfamLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanelPrincipal.add(jPanel1);

        jPanel2.setBackground(new java.awt.Color(0, 51, 102));
        jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));

        jButtonEnviar.setBackground(new java.awt.Color(204, 204, 204));
        jButtonEnviar.setForeground(new java.awt.Color(0, 0, 0));
        jButtonEnviar.setText("Enviar");
        jButtonEnviar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonEnviarMouseClicked(evt);
            }
        });
        jButtonEnviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEnviarActionPerformed(evt);
            }
        });

        comboBoxTemperatura.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 14)); // NOI18N
        comboBoxTemperatura.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "17", "18", "19", "20", "21", "22", "23", "24", "25" }));
        comboBoxTemperatura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxTemperaturaActionPerformed(evt);
            }
        });

        jLabelTemperatura1.setBackground(new java.awt.Color(255, 255, 255));
        jLabelTemperatura1.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 24)); // NOI18N
        jLabelTemperatura1.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTemperatura1.setText("Ar-condicionado");
        jLabelTemperatura1.setToolTipText("");

        jLabelTemperatura2.setBackground(new java.awt.Color(255, 255, 255));
        jLabelTemperatura2.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 18)); // NOI18N
        jLabelTemperatura2.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTemperatura2.setText("Temperatura:");
        jLabelTemperatura2.setToolTipText("");

        jLabelModo.setBackground(new java.awt.Color(255, 255, 255));
        jLabelModo.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 18)); // NOI18N
        jLabelModo.setForeground(new java.awt.Color(255, 255, 255));
        jLabelModo.setText("Modo:");
        jLabelModo.setToolTipText("");

        comboBoxModo.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 14)); // NOI18N
        comboBoxModo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cool", "Fan", "Auto", "Dry" }));
        comboBoxModo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxModoActionPerformed(evt);
            }
        });

        jLabelDS2.setBackground(new java.awt.Color(255, 255, 255));
        jLabelDS2.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 24)); // NOI18N
        jLabelDS2.setForeground(new java.awt.Color(255, 255, 255));
        jLabelDS2.setText("Data-show");
        jLabelDS2.setToolTipText("");

        jLabelBaixo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/dataShow/para-baixo.PNG"))); // NOI18N
        jLabelBaixo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelBaixoMouseClicked(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabelBaixoMouseReleased(evt);
            }
        });

        jLabelOkey.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/dataShow/ok.PNG"))); // NOI18N
        jLabelOkey.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelOkeyMouseClicked(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabelOkeyMouseReleased(evt);
            }
        });

        jLabelCima.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/dataShow/para-cima.PNG"))); // NOI18N
        jLabelCima.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelCimaMouseClicked(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabelCimaMouseReleased(evt);
            }
        });

        jLabelDireita.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/dataShow/direita.PNG"))); // NOI18N
        jLabelDireita.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelDireitaMouseClicked(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabelDireitaMouseReleased(evt);
            }
        });

        jLabelEsquerda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/dataShow/esquerda.PNG"))); // NOI18N
        jLabelEsquerda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelEsquerdaMouseClicked(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabelEsquerdaMouseReleased(evt);
            }
        });

        jLabelEsc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/dataShow/esc.PNG"))); // NOI18N
        jLabelEsc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelEscMouseClicked(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabelEscMouseReleased(evt);
            }
        });

        jLabelFreeze.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/dataShow/freeze.PNG"))); // NOI18N
        jLabelFreeze.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelFreezeMouseClicked(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabelFreezeMouseReleased(evt);
            }
        });

        jLabelMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/dataShow/menu.PNG"))); // NOI18N
        jLabelMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelMenuMouseClicked(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabelMenuMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(177, 177, 177)
                        .addComponent(jLabelBaixo, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelTemperatura1)
                            .addComponent(jLabelDS2)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jLabelFreeze)
                        .addGap(83, 83, 83)
                        .addComponent(jLabelEsc))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(176, 176, 176)
                        .addComponent(jLabelCima, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelMenu)
                .addGap(34, 34, 34))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(115, 115, 115)
                .addComponent(jLabelEsquerda)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelOkey, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelDireita, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(47, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabelModo)
                            .addComponent(jLabelTemperatura2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(comboBoxTemperatura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(comboBoxModo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(170, 170, 170))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jButtonEnviar, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(188, 188, 188))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabelTemperatura1)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboBoxTemperatura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelTemperatura2))
                .addGap(33, 33, 33)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelModo)
                    .addComponent(comboBoxModo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButtonEnviar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelDS2)
                .addGap(14, 14, 14)
                .addComponent(jLabelCima)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabelOkey, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelEsquerda, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabelDireita)
                        .addGap(19, 19, 19)))
                .addComponent(jLabelBaixo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 71, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelEsc)
                    .addComponent(jLabelMenu)
                    .addComponent(jLabelFreeze))
                .addGap(16, 16, 16))
        );

        jPanelPrincipal.add(jPanel2);

        getContentPane().add(jPanelPrincipal);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void comboBoxTemperaturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxTemperaturaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboBoxTemperaturaActionPerformed

    private void comboBoxModoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxModoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboBoxModoActionPerformed

    private void jButtonEnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEnviarActionPerformed
        // botão que envia as informaçoes do ar-condicionado dos comboBox's
        String funcao = "AR";
        if(comboBoxModo.getSelectedItem().equals("AUTO") || comboBoxModo.getSelectedItem().equals("FAN")){
            funcao += (String) comboBoxModo.getSelectedItem();
        }else{
            funcao += (String) comboBoxModo.getSelectedItem();
            funcao += (String) comboBoxTemperatura.getSelectedItem();
        }
        
        funcao += ".";
        MainApp.sessao.trataAcao(funcao, nsala);
    }//GEN-LAST:event_jButtonEnviarActionPerformed

    private void jLabelArMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelArMouseClicked
        // liga ou desliga a depender se o estado é true ou false
        if (estadoAr) {
            MainApp.sessao.trataAcao("AROFF.", nsala);
            jLabelAr.setIcon(new ImageIcon(getClass().getResource("/Imagens/ar-condicionado-off (1).png")));
        } else {
            MainApp.sessao.trataAcao("ARON.", nsala);
            jLabelAr.setIcon(new ImageIcon(getClass().getResource("/Imagens/ar-condicionado-on (1).png")));
        }
    }//GEN-LAST:event_jLabelArMouseClicked

    private void jLabelLuzMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelLuzMouseClicked
        // liga ou desliga a depender se o estado é true ou false
        if (estadoLuzes) {
            MainApp.sessao.trataAcao("LZOFF.", nsala);
            jLabelLuz.setIcon(new ImageIcon(getClass().getResource("/Imagens/luz-off (1).png")));
        } else {
            MainApp.sessao.trataAcao("LZON.", nsala);
            jLabelLuz.setIcon(new ImageIcon(getClass().getResource("/Imagens/luz-on (1).png")));
        }
    }//GEN-LAST:event_jLabelLuzMouseClicked

    private void jLabelDSMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelDSMouseClicked
        // liga ou desliga a depender se o estado é true ou false
        if (estadoDS) {
            MainApp.sessao.trataAcao("DSOFF.", nsala);
            jLabelDS.setIcon(new ImageIcon(getClass().getResource("/Imagens/data-show-off (1).png")));
        } else {
            MainApp.sessao.trataAcao("DSON.", nsala);
            jLabelDS.setIcon(new ImageIcon(getClass().getResource("/Imagens/data-show-on (1).png")));
        }
    }//GEN-LAST:event_jLabelDSMouseClicked

    private void jLabelFreezeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelFreezeMouseClicked
        // TODO add your handling code here:
        if (estadoDS) {
            MainApp.sessao.trataAcao("DSFREEZE.", nsala);
            jLabelFreeze.setIcon(new ImageIcon(getClass().getResource("/Imagens/dataShow/freeze-pressionado.png")));
        } else {

        }
    }//GEN-LAST:event_jLabelFreezeMouseClicked

    private void jLabelFreezeMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelFreezeMouseReleased
        // TODO add your handling code here:
        jLabelFreeze.setIcon(new ImageIcon(getClass().getResource("/Imagens/dataShow/freeze.png")));
    }//GEN-LAST:event_jLabelFreezeMouseReleased

    private void jLabelEscMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelEscMouseClicked
        // TODO add your handling code here:
        if (estadoDS) {
            MainApp.sessao.trataAcao("DSESC.", nsala);
            jLabelEsc.setIcon(new ImageIcon(getClass().getResource("/Imagens/dataShow/esc-pressionado.png")));
        } else {

        }
    }//GEN-LAST:event_jLabelEscMouseClicked

    private void jLabelEscMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelEscMouseReleased
        // TODO add your handling code here:
        jLabelEsc.setIcon(new ImageIcon(getClass().getResource("/Imagens/dataShow/esc.png")));
    }//GEN-LAST:event_jLabelEscMouseReleased

    private void jLabelMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelMenuMouseClicked
        // TODO add your handling code here:
        if (estadoDS) {
            MainApp.sessao.trataAcao("DSMENU.", nsala);
            jLabelMenu.setIcon(new ImageIcon(getClass().getResource("/Imagens/dataShow/menu-pressionado.png")));
        }
    }//GEN-LAST:event_jLabelMenuMouseClicked

    private void jLabelMenuMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelMenuMouseReleased
        // TODO add your handling code here:
        jLabelMenu.setIcon(new ImageIcon(getClass().getResource("/Imagens/dataShow/menu.png")));

    }//GEN-LAST:event_jLabelMenuMouseReleased

    private void jLabelCimaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelCimaMouseClicked
        // TODO add your handling code here:
        if (estadoDS) {
            MainApp.sessao.trataAcao("DSCIMA.", nsala);
            jLabelCima.setIcon(new ImageIcon(getClass().getResource("/Imagens/dataShow/para-cima-pressionado.png")));
        }
    }//GEN-LAST:event_jLabelCimaMouseClicked

    private void jLabelCimaMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelCimaMouseReleased
        // TODO add your handling code here:
        jLabelCima.setIcon(new ImageIcon(getClass().getResource("/Imagens/dataShow/para-cima.png")));
    }//GEN-LAST:event_jLabelCimaMouseReleased

    private void jLabelEsquerdaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelEsquerdaMouseClicked
        // TODO add your handling code here:
        if (estadoDS) {
            MainApp.sessao.trataAcao("DSESQ.", nsala);
            jLabelEsquerda.setIcon(new ImageIcon(getClass().getResource("/Imagens/dataShow/esquerda-pressionado.png")));
        }
    }//GEN-LAST:event_jLabelEsquerdaMouseClicked

    private void jLabelEsquerdaMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelEsquerdaMouseReleased
        // TODO add your handling code here:
        jLabelEsquerda.setIcon(new ImageIcon(getClass().getResource("/Imagens/dataShow/esquerda.png")));
    }//GEN-LAST:event_jLabelEsquerdaMouseReleased

    private void jLabelBaixoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelBaixoMouseClicked
        // TODO add your handling code here:
        if (estadoDS) {
            MainApp.sessao.trataAcao("DSBAIXO.", nsala);
            jLabelEsquerda.setIcon(new ImageIcon(getClass().getResource("/Imagens/dataShow/para-baixo-pressionado.png")));
        }
    }//GEN-LAST:event_jLabelBaixoMouseClicked

    private void jLabelBaixoMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelBaixoMouseReleased
        // TODO add your handling code here:
        jLabelEsquerda.setIcon(new ImageIcon(getClass().getResource("/Imagens/dataShow/para-baixo.png")));
    }//GEN-LAST:event_jLabelBaixoMouseReleased

    private void jLabelDireitaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelDireitaMouseClicked
        // TODO add your handling code here:
        if (estadoDS) {
            MainApp.sessao.trataAcao("DSDIR.", nsala);
            jLabelEsquerda.setIcon(new ImageIcon(getClass().getResource("/Imagens/dataShow/direita-pressionado.png")));
        }
    }//GEN-LAST:event_jLabelDireitaMouseClicked

    private void jLabelDireitaMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelDireitaMouseReleased
        // TODO add your handling code here:
        jLabelEsquerda.setIcon(new ImageIcon(getClass().getResource("/Imagens/dataShow/direita.png")));
    }//GEN-LAST:event_jLabelDireitaMouseReleased

    private void jLabelOkeyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelOkeyMouseClicked
        // TODO add your handling code here:
        if (estadoDS) {
            MainApp.sessao.trataAcao("DSOK.", nsala);
            jLabelEsquerda.setIcon(new ImageIcon(getClass().getResource("/Imagens/dataShow/ok-pressionado.png")));
        }
    }//GEN-LAST:event_jLabelOkeyMouseClicked

    private void jLabelOkeyMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelOkeyMouseReleased
        // TODO add your handling code here:
        jLabelEsquerda.setIcon(new ImageIcon(getClass().getResource("/Imagens/dataShow/ok.png")));
    }//GEN-LAST:event_jLabelOkeyMouseReleased

    private void jButtonEnviarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonEnviarMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonEnviarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameSala.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameSala.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameSala.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameSala.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameSala(0).setVisible(true);
            }
        });
    }

    private class AtualizaDadosSala implements Runnable {

        @Override
        public void run() {
            while (isDisplayable()) {
                String resposta = MainApp.sessao.getSala(nsala);
                if (resposta.contains("nSala")) {
                    sala = gs.fromJson(resposta, tipoSala);
                    SwingUtilities.invokeLater(new Runnable() {
                        @Override
                        public void run() {
                            jLabelTemperaturaValor.setText(sala.getTemperatura() + "ºC");
                            jLabelHumidadeValor.setText(sala.getUmidade() + "%");
                            if (sala.isPresenca()) {
                                jLabelPresencaValor.setText("Com movimento");
                            } else {
                                jLabelPresencaValor.setText("Sem movimento");
                            }
                            estadoAr = sala.isEstadoAr();
                            estadoDS = sala.isEstadoDataShow();
                            estadoLuzes = sala.isEstadoLuzes();
                            /*if (!estadoAr) {
                                jLabelAr.setIcon(new ImageIcon(getClass().getResource("/Imagens/ar-condicionado-off (1).png")));
                            } else {
                                
                                jLabelAr.setIcon(new ImageIcon(getClass().getResource("/Imagens/ar-condicionado-on (1).png")));
                            }
                            if (!estadoLuzes) {
                                jLabelLuz.setIcon(new ImageIcon(getClass().getResource("/Imagens/luz-off (1).png")));
                            } else {
                                jLabelLuz.setIcon(new ImageIcon(getClass().getResource("/Imagens/luz-on (1).png")));
                            }
                            if (!estadoDS) {
                              
                                jLabelDS.setIcon(new ImageIcon(getClass().getResource("/Imagens/data-show-off (1).png")));
                            } else {
                                
                                jLabelDS.setIcon(new ImageIcon(getClass().getResource("/Imagens/data-show-on (1).png")));
                            }*/
                        }
                    });
                }
                try {
                    Thread.sleep(3000);
                } catch (InterruptedException ex) {
                    System.out.println("Erro ao atualizar");
                }

            }

            MainApp.sessao.trataAcao("DSC", nsala);
            
            SalaPanel.salaAberta = false;
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> comboBoxModo;
    private javax.swing.JComboBox<String> comboBoxTemperatura;
    private javax.swing.JButton jButtonEnviar;
    private javax.swing.JLabel jLabelAr;
    private javax.swing.JLabel jLabelBaixo;
    private javax.swing.JLabel jLabelCima;
    private javax.swing.JLabel jLabelDS;
    private javax.swing.JLabel jLabelDS2;
    private javax.swing.JLabel jLabelDireita;
    private javax.swing.JLabel jLabelEsc;
    private javax.swing.JLabel jLabelEsquerda;
    private javax.swing.JLabel jLabelFreeze;
    private javax.swing.JLabel jLabelHumidade;
    private javax.swing.JLabel jLabelHumidadeValor;
    private javax.swing.JLabel jLabelIfamLogo;
    private javax.swing.JLabel jLabelLuz;
    private javax.swing.JLabel jLabelMenu;
    private javax.swing.JLabel jLabelModo;
    private javax.swing.JLabel jLabelOkey;
    private javax.swing.JLabel jLabelPresencaValor;
    private javax.swing.JLabel jLabelPresença;
    private javax.swing.JLabel jLabelSala;
    private javax.swing.JLabel jLabelTemperatura;
    private javax.swing.JLabel jLabelTemperatura1;
    private javax.swing.JLabel jLabelTemperatura2;
    private javax.swing.JLabel jLabelTemperaturaValor;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanelPrincipal;
    // End of variables declaration//GEN-END:variables
}
