/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Aplicacao;

import Modelo.Acao;
import com.google.gson.Gson;
import com.google.gson.reflect.TypeToken;
import javax.swing.Box;
import java.awt.Dimension;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.util.ArrayList;
import java.util.Collections;
import java.util.List;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import java.util.Collections;
import javax.swing.SwingUtilities;

/**
 *
 * @author LENOVO
 */
public class PAAcoes extends javax.swing.JFrame {

    private List<Acao> acoes;
    private List<AcoesPanel> acoesP;
    private Gson gs;
    private java.lang.reflect.Type tipoAcao;
    private int tAcaoes;
    private volatile boolean runningUpdate = true;
    private Thread updateThread;

    /**
     * Creates new form PAgendamento
     */
    public PAAcoes() {
        initComponents();
        this.setExtendedState(MAXIMIZED_BOTH);
        gs = new Gson();
        acoes = new ArrayList<>();
        acoesP = new ArrayList<>();
        tipoAcao = new TypeToken<ArrayList<Acao>>() {
        }.getType();
        adicionarAcoes();
        updateThread = new Thread(new AtualizaDadosAcao());
        updateThread.start();

    }

    public void adicionarAcoes() {
        jPanelAcoes.removeAll();
        String resp = MainApp.sessao.logs();
        acoes = gs.fromJson(resp, tipoAcao);
        ordenarAcoes(acoes);
        tAcaoes = acoes.size();
        for (Acao acao : acoes) {
            if (acao.getnSala() == -1) {
                AcoesPanel pa = new AcoesPanel(acao.getLogin(), acao.getTipoAcao(),
                        acao.dataFormatada(), acao.horaFormatada(), acao.getIdAcao());
                jPanelAcoes.add(pa);
                acoesP.add(pa);
            } else {
                AcoesPanel pa = new AcoesPanel(acao.getLogin(), acao.getTipoAcao(),
                        acao.dataFormatada(), acao.horaFormatada(), acao.getIdAcao(), acao.getnSala());
                jPanelAcoes.add(pa);
                acoesP.add(pa);
            }
        }

    }

    public void ordenarAcoes(List<Acao> acoes) {
        Collections.sort(acoes, (a1, a2) -> {
            int dataR = a2.getDataAcao().compareTo(a1.getDataAcao());
            if (dataR != 0) {
                return dataR;
            }
            return a2.getHoraAcao().compareTo(a1.getHoraAcao());
        });
    }

    public void stopUpdateThread() {
        runningUpdate = false; // Sinaliza para a thread parar
        if (updateThread != null && updateThread.isAlive()) {
            // Opcional, mas recomendado: interrompe o sleep
            updateThread.interrupt();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPaneAcoes = new javax.swing.JScrollPane();
        jPanelAcoes = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabelIDEd = new javax.swing.JLabel();
        jLabelAutor = new javax.swing.JLabel();
        jLabelData = new javax.swing.JLabel();
        jLabelHora = new javax.swing.JLabel();
        jLabelTipoAcao = new javax.swing.JLabel();
        jLabelAutorEd = new javax.swing.JLabel();
        jLabelTipoAcaoEd = new javax.swing.JLabel();
        jLabelDataEd = new javax.swing.JLabel();
        jLabelHoraEd = new javax.swing.JLabel();
        jLabelID = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabelSala = new javax.swing.JLabel();
        jLabelSalaEd = new javax.swing.JLabel();
        jLabelAgendamentos = new javax.swing.JLabel();
        jLabelIF1 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabelIfamLogo1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuLogo = new javax.swing.JMenu();
        jMenuSalas = new javax.swing.JMenu();
        jMenuAgendamento = new javax.swing.JMenu();
        jMenuAcaoes = new javax.swing.JMenu();
        jMenuDIR = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridLayout(1, 0));

        jPanel1.setBackground(new java.awt.Color(0, 51, 102));

        jScrollPaneAcoes.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPaneAcoes.setMaximumSize(new java.awt.Dimension(500, 32767));

        jPanelAcoes.setBackground(new java.awt.Color(0, 51, 102));
        jPanelAcoes.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanelAcoes.setLayout(new javax.swing.BoxLayout(jPanelAcoes, javax.swing.BoxLayout.Y_AXIS));

        jPanel3.setBackground(new java.awt.Color(153, 153, 153));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel3.setMaximumSize(new java.awt.Dimension(1343, 81));
        jPanel3.setMinimumSize(new java.awt.Dimension(1343, 81));

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jLabelIDEd.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 14)); // NOI18N
        jLabelIDEd.setForeground(new java.awt.Color(0, 0, 0));
        jLabelIDEd.setText("XXXX");

        jLabelAutor.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 14)); // NOI18N
        jLabelAutor.setForeground(new java.awt.Color(0, 0, 0));
        jLabelAutor.setText("Usúario:");

        jLabelData.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 14)); // NOI18N
        jLabelData.setForeground(new java.awt.Color(0, 0, 0));
        jLabelData.setText("Data: ");

        jLabelHora.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 14)); // NOI18N
        jLabelHora.setForeground(new java.awt.Color(0, 0, 0));
        jLabelHora.setText("Hora:");

        jLabelTipoAcao.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 14)); // NOI18N
        jLabelTipoAcao.setForeground(new java.awt.Color(0, 0, 0));
        jLabelTipoAcao.setText("Tipo ação:");

        jLabelAutorEd.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 14)); // NOI18N
        jLabelAutorEd.setForeground(new java.awt.Color(0, 0, 0));
        jLabelAutorEd.setText("XXXXXXXXX");

        jLabelTipoAcaoEd.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 14)); // NOI18N
        jLabelTipoAcaoEd.setForeground(new java.awt.Color(0, 0, 0));
        jLabelTipoAcaoEd.setText("XXXXXXXXX");

        jLabelDataEd.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 14)); // NOI18N
        jLabelDataEd.setForeground(new java.awt.Color(0, 0, 0));
        jLabelDataEd.setText("XXXXXXXXX");

        jLabelHoraEd.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 14)); // NOI18N
        jLabelHoraEd.setForeground(new java.awt.Color(0, 0, 0));
        jLabelHoraEd.setText("XXXXXXXXX");

        jLabelID.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 14)); // NOI18N
        jLabelID.setForeground(new java.awt.Color(0, 0, 0));
        jLabelID.setText("ID:");

        jSeparator2.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jLabelSala.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 14)); // NOI18N
        jLabelSala.setForeground(new java.awt.Color(0, 0, 0));
        jLabelSala.setText("Sala:");

        jLabelSalaEd.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 14)); // NOI18N
        jLabelSalaEd.setForeground(new java.awt.Color(0, 0, 0));
        jLabelSalaEd.setText("XXXXXXXXX");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabelTipoAcao)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelTipoAcaoEd)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabelAutor)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelAutorEd)
                        .addGap(10, 10, 10)))
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelHora)
                    .addComponent(jLabelData))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelDataEd)
                    .addComponent(jLabelHoraEd))
                .addGap(18, 18, 18)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabelID)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelIDEd)
                        .addContainerGap())
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabelSala)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabelSalaEd)
                        .addContainerGap(838, Short.MAX_VALUE))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabelData, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabelDataEd))
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabelAutor)
                                .addComponent(jLabelAutorEd)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabelHora)
                                .addComponent(jLabelHoraEd))
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabelTipoAcao)
                                .addComponent(jLabelTipoAcaoEd)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelSala, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelSalaEd))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelIDEd)
                            .addComponent(jLabelID))))
                .addContainerGap())
        );

        jPanelAcoes.add(jPanel3);

        jPanelAcoes.add(Box.createRigidArea(new Dimension(0,20)));

        jScrollPaneAcoes.setViewportView(jPanelAcoes);

        jLabelAgendamentos.setBackground(new java.awt.Color(255, 255, 255));
        jLabelAgendamentos.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 36)); // NOI18N
        jLabelAgendamentos.setForeground(new java.awt.Color(255, 255, 255));
        jLabelAgendamentos.setText("Ações");

        jLabelIF1.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 20)); // NOI18N
        jLabelIF1.setForeground(new java.awt.Color(255, 255, 255));
        jLabelIF1.setText("IFControl 3.0");

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/lupa.png"))); // NOI18N
        jButton3.setText("Pesquisar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabelIfamLogo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/IFAM_logo.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton3))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabelIfamLogo1))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPaneAcoes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabelAgendamentos)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabelIF1)))))
                .addGap(27, 27, 27))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelIF1)
                    .addComponent(jLabelAgendamentos))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPaneAcoes, javax.swing.GroupLayout.DEFAULT_SIZE, 497, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelIfamLogo1, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getContentPane().add(jPanel1);

        jMenuLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/IFControl3_logoMini.png"))); // NOI18N
        jMenuBar1.add(jMenuLogo);

        jMenuSalas.setText("Salas");
        jMenuSalas.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
            }
            public void menuSelected(javax.swing.event.MenuEvent evt) {
                jMenuSalasMenuSelected(evt);
            }
        });
        jMenuSalas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuSalasActionPerformed(evt);
            }
        });
        jMenuBar1.add(jMenuSalas);

        jMenuAgendamento.setText("Agendamentos");
        jMenuAgendamento.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
            }
            public void menuSelected(javax.swing.event.MenuEvent evt) {
                jMenuAgendamentoMenuSelected(evt);
            }
        });
        jMenuBar1.add(jMenuAgendamento);

        jMenuAcaoes.setText("Ações");
        jMenuAcaoes.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
            }
            public void menuSelected(javax.swing.event.MenuEvent evt) {
                jMenuAcaoesMenuSelected(evt);
            }
        });
        jMenuBar1.add(jMenuAcaoes);

        jMenuDIR.setText("Dispositivos IR");
        jMenuDIR.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
            }
            public void menuSelected(javax.swing.event.MenuEvent evt) {
                jMenuDIRMenuSelected(evt);
            }
        });
        jMenuBar1.add(jMenuDIR);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuSalasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuSalasActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_jMenuSalasActionPerformed

    private void jMenuSalasMenuSelected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_jMenuSalasMenuSelected
        // TODO add your handling code here:
        stopUpdateThread();
        dispose();
        MainApp.showPSalas();

    }//GEN-LAST:event_jMenuSalasMenuSelected

    private void jMenuAgendamentoMenuSelected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_jMenuAgendamentoMenuSelected
        // TODO add your handling code here:
        stopUpdateThread();
        dispose();
        MainApp.showPAngendamento();
    }//GEN-LAST:event_jMenuAgendamentoMenuSelected

    private void jMenuDIRMenuSelected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_jMenuDIRMenuSelected
        // TODO add your handling code here:
        stopUpdateThread();
        dispose();
        MainApp.showPDispositivos();
    }//GEN-LAST:event_jMenuDIRMenuSelected

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        MainApp.showPesquisarAcao();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jMenuAcaoesMenuSelected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_jMenuAcaoesMenuSelected
        // TODO add your handling code here:

    }//GEN-LAST:event_jMenuAcaoesMenuSelected

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PAAcoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PAAcoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PAAcoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PAAcoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PAAcoes().setVisible(true);
            }
        });
    }

    private class AtualizaDadosAcao implements Runnable {

        public boolean procurarPanel(Acao acao) {
            for (AcoesPanel panel : acoesP) {
                if (panel.getId() == acao.getIdAcao()) {
                    return true;
                }
            }
            return false;
        }

        @Override
        public void run() {
            while (runningUpdate) {
                String resp = MainApp.sessao.logs();
                if (resp.contains("dataAcao")) {
                    acoes = gs.fromJson(resp, tipoAcao);
                    ordenarAcoes(acoes);
                    SwingUtilities.invokeLater(new Runnable() {
                        @Override
                        public void run() {
                            if (tAcaoes < acoes.size()) {
                                jPanelAcoes.removeAll();
                                for (Acao acao : acoes) {
                                    if (acao.getnSala() == -1) {
                                        AcoesPanel pa = new AcoesPanel(acao.getLogin(), acao.getTipoAcao(),
                                                acao.dataFormatada(), acao.horaFormatada(), acao.getIdAcao());
                                        jPanelAcoes.add(pa);
                                        acoesP.add(pa);
                                    } else {
                                        AcoesPanel pa = new AcoesPanel(acao.getLogin(), acao.getTipoAcao(),
                                                acao.dataFormatada(), acao.horaFormatada(), acao.getIdAcao(), acao.getnSala());
                                        jPanelAcoes.add(pa);
                                        acoesP.add(pa);
                                    }

                                }
                                jPanelAcoes.revalidate();
                                jPanelAcoes.repaint();
                            }
                        }
                    }
                    );

                }
                try {
                    Thread.sleep(5000);
                } catch (InterruptedException ex) {
                    System.out.println("Erro ao atualizar");
                }

            }

        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabelAgendamentos;
    private javax.swing.JLabel jLabelAutor;
    private javax.swing.JLabel jLabelAutorEd;
    private javax.swing.JLabel jLabelData;
    private javax.swing.JLabel jLabelDataEd;
    private javax.swing.JLabel jLabelHora;
    private javax.swing.JLabel jLabelHoraEd;
    private javax.swing.JLabel jLabelID;
    private javax.swing.JLabel jLabelIDEd;
    private javax.swing.JLabel jLabelIF1;
    private javax.swing.JLabel jLabelIfamLogo1;
    private javax.swing.JLabel jLabelSala;
    private javax.swing.JLabel jLabelSalaEd;
    private javax.swing.JLabel jLabelTipoAcao;
    private javax.swing.JLabel jLabelTipoAcaoEd;
    private javax.swing.JMenu jMenuAcaoes;
    private javax.swing.JMenu jMenuAgendamento;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuDIR;
    private javax.swing.JMenu jMenuLogo;
    private javax.swing.JMenu jMenuSalas;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanelAcoes;
    private javax.swing.JScrollPane jScrollPaneAcoes;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    // End of variables declaration//GEN-END:variables
}
