/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Aplicacao;
import Modelo.Agendamento;
import Modelo.Sala;

import com.google.gson.Gson;
import com.google.gson.reflect.TypeToken;
import javax.swing.Box;
import java.awt.Dimension;
import static java.awt.Frame.MAXIMIZED_BOTH;
import java.util.List;
import javax.swing.SwingUtilities;
/**
 *
 * @author LENOVO
 */
public class PAgendamento extends javax.swing.JFrame {
    private List<AgendamentoPanel> agendamentoP;
    private List<Agendamento> agendamentos;
    private Gson gs;
    private java.lang.reflect.Type tipoAgendamento;
    /**
     * Creates new form PAgendamento
     */
    public PAgendamento() {
        initComponents();
        this.setExtendedState(MAXIMIZED_BOTH);
        gs = new Gson();
        tipoAgendamento = new TypeToken<List<Agendamento>>() {
        }.getType();
        new Thread(new PAgendamento.AtualizaDadosAgendamento()).start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPaneAgendamentos = new javax.swing.JScrollPane();
        jPanelAgendamentos = new javax.swing.JPanel();
        jLabelAgendamentos = new javax.swing.JLabel();
        jLabelIF1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabelIfamLogo1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuLogo = new javax.swing.JMenu();
        jMenuSalas = new javax.swing.JMenu();
        jMenuAgendamento = new javax.swing.JMenu();
        jMenuAcaoes = new javax.swing.JMenu();
        jMenuDIR = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridLayout(1, 0));

        jPanel1.setBackground(new java.awt.Color(0, 51, 102));

        jScrollPaneAgendamentos.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPaneAgendamentos.setMaximumSize(new java.awt.Dimension(500, 32767));

        jPanelAgendamentos.setBackground(new java.awt.Color(0, 51, 102));
        jPanelAgendamentos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanelAgendamentos.setLayout(new javax.swing.BoxLayout(jPanelAgendamentos, javax.swing.BoxLayout.Y_AXIS));

        jPanelAgendamentos.add(Box.createRigidArea(new Dimension(0,20)));

        jScrollPaneAgendamentos.setViewportView(jPanelAgendamentos);

        jLabelAgendamentos.setBackground(new java.awt.Color(255, 255, 255));
        jLabelAgendamentos.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 36)); // NOI18N
        jLabelAgendamentos.setForeground(new java.awt.Color(255, 255, 255));
        jLabelAgendamentos.setText("Agendamentos");

        jLabelIF1.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 20)); // NOI18N
        jLabelIF1.setForeground(new java.awt.Color(255, 255, 255));
        jLabelIF1.setText("IFControl 3.0");

        jButton2.setBackground(new java.awt.Color(0, 51, 102));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/mais.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabelIfamLogo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/IFAM_logo.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabelIfamLogo1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPaneAgendamentos, javax.swing.GroupLayout.DEFAULT_SIZE, 1343, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabelAgendamentos)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 940, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jButton2)
                                    .addComponent(jLabelIF1))))))
                .addGap(27, 27, 27))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabelIF1)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2))
                    .addComponent(jLabelAgendamentos))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPaneAgendamentos, javax.swing.GroupLayout.DEFAULT_SIZE, 497, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelIfamLogo1, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getContentPane().add(jPanel1);

        jMenuLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/IFControl3_logoMini.png"))); // NOI18N
        jMenuBar1.add(jMenuLogo);

        jMenuSalas.setText("Salas");
        jMenuSalas.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
            }
            public void menuSelected(javax.swing.event.MenuEvent evt) {
                jMenuSalasMenuSelected(evt);
            }
        });
        jMenuSalas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuSalasActionPerformed(evt);
            }
        });
        jMenuBar1.add(jMenuSalas);

        jMenuAgendamento.setText("Agendamentos");
        jMenuAgendamento.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
            }
            public void menuSelected(javax.swing.event.MenuEvent evt) {
                jMenuAgendamentoMenuSelected(evt);
            }
        });
        jMenuBar1.add(jMenuAgendamento);

        jMenuAcaoes.setText("Ações");
        jMenuAcaoes.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
            }
            public void menuSelected(javax.swing.event.MenuEvent evt) {
                jMenuAcaoesMenuSelected(evt);
            }
        });
        jMenuBar1.add(jMenuAcaoes);

        jMenuDIR.setText("Dispositivos IR");
        jMenuDIR.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
            }
            public void menuSelected(javax.swing.event.MenuEvent evt) {
                jMenuDIRMenuSelected(evt);
            }
        });
        jMenuBar1.add(jMenuDIR);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuSalasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuSalasActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jMenuSalasActionPerformed

    private void jMenuSalasMenuSelected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_jMenuSalasMenuSelected
        // TODO add your handling code here:
        dispose();
        MainApp.showPSalas();
    }//GEN-LAST:event_jMenuSalasMenuSelected

    private void jMenuAgendamentoMenuSelected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_jMenuAgendamentoMenuSelected
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuAgendamentoMenuSelected

    private void jMenuAcaoesMenuSelected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_jMenuAcaoesMenuSelected
        // TODO add your handling code here:
        dispose();
        MainApp.showPAAcoes();
    }//GEN-LAST:event_jMenuAcaoesMenuSelected

    private void jMenuDIRMenuSelected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_jMenuDIRMenuSelected
        // TODO add your handling code here:
        dispose();
        MainApp.showPDispositivos();
    }//GEN-LAST:event_jMenuDIRMenuSelected

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        MainApp.showAddAgendamento();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PAgendamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PAgendamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PAgendamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PAgendamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PAgendamento().setVisible(true);
            }
        });
    }
    
    private class AtualizaDadosAgendamento implements Runnable{
        
        public AgendamentoPanel procurarAP(Agendamento agen) {
            for (AgendamentoPanel ap : agendamentoP) {
                if (ap.getIdAgendamento()==agen.getIdAgendamento()) {
                    return ap;
                }
            }
            System.out.println("Não foi posssivel encontrar nem um Panel para o agendamento: " + agen.getIdAgendamento());
            return null;
        }
        
        @Override
        public void run() {
            while(isDisplayable()){
                String resp=MainApp.sessao.verificarResposta();
                if(resp.contains("--modAgendamento--")){
                    String parte[]=resp.split("--modAgendamento--");
                    agendamentos = gs.fromJson(parte[1],tipoAgendamento);
                    SwingUtilities.invokeLater(new Runnable() {
                        @Override
                        public void run() {
                             for(Agendamento agen:agendamentos){
                                 AgendamentoPanel agenP=procurarAP(agen);
                                 if(agenP==null){
                                    AgendamentoPanel novoP=new AgendamentoPanel(agen.getIdAgendamento(),agen.getAutor(), 
                                            agen.getTitulo(), agen.getDataIn(), agen.getDataF(),agen.gethAtv(), agen.gethDesat(), agen.getDiaSemana(), 
                                            agen.getSalas(), agen.getDispositivos());
                                    agendamentoP.add(novoP);
                                    jPanelAgendamentos.add(novoP);
                                 }else{
                                     agenP.atualizar(agen.getAutor(), 
                                            agen.getTitulo(), agen.getDataIn(), agen.getDataF(),agen.gethAtv(), agen.gethDesat(), agen.getDiaSemana(), 
                                            agen.getSalas(), agen.getDispositivos());
                                 }
                             }
                        }
                    });
                }
            }
        }
    
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabelAgendamentos;
    private javax.swing.JLabel jLabelIF1;
    private javax.swing.JLabel jLabelIfamLogo1;
    private javax.swing.JMenu jMenuAcaoes;
    private javax.swing.JMenu jMenuAgendamento;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuDIR;
    private javax.swing.JMenu jMenuLogo;
    private javax.swing.JMenu jMenuSalas;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelAgendamentos;
    private javax.swing.JScrollPane jScrollPaneAgendamentos;
    // End of variables declaration//GEN-END:variables
}
