/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Aplicacao;

import Modelo.Acao;

import com.google.gson.Gson;
import com.google.gson.reflect.TypeToken;
import java.sql.Time;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.List;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author LENOVO
 */
public class PesquisarAcao extends javax.swing.JFrame {

    private Gson gs;
    private java.lang.reflect.Type tipoAcao;

    /**
     * Creates new form AddSala
     */
    public PesquisarAcao() {
        initComponents();
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        tipoAcao = new TypeToken<ArrayList<Acao>>() {
        }.getType();
        gs = new Gson();

    }

    public String procurarTipoAcao(String texto) {
        String regex = "\\((.*?)\\)";

        Pattern pattern = Pattern.compile(regex);
        Matcher matcher = pattern.matcher(texto);

        if (matcher.find()) {
            // Retorna o conteúdo do primeiro grupo de captura (o que está dentro do (.*?) )
            System.out.println(matcher.group(1));

            return matcher.group(1);

        } else {
            return null;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabelIF = new javax.swing.JLabel();
        jLabelIfamLogo = new javax.swing.JLabel();
        jButtonCancelar = new javax.swing.JButton();
        jLabelProcurarAcao = new javax.swing.JLabel();
        jLabelAutor = new javax.swing.JLabel();
        jLabelTipoAcao = new javax.swing.JLabel();
        jTextFielAutor = new javax.swing.JTextField();
        jButtonProcurar = new javax.swing.JButton();
        jLabelData = new javax.swing.JLabel();
        jLabelHora = new javax.swing.JLabel();
        jDataInicio1 = new com.toedter.calendar.JDateChooser();
        jSpinnerHora = new javax.swing.JSpinner();
        jLabelSeparatorHoraIn = new javax.swing.JLabel();
        jSpinnerMinutos = new javax.swing.JSpinner();
        jLabelSala = new javax.swing.JLabel();
        jTextFieldSala = new javax.swing.JTextField();
        jComboBoxTipoAcao = new javax.swing.JComboBox<>();
        jCheckBox1 = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridLayout(1, 0));

        jPanel1.setBackground(new java.awt.Color(0, 51, 102));

        jLabelIF.setBackground(new java.awt.Color(187, 187, 187));
        jLabelIF.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 18)); // NOI18N
        jLabelIF.setForeground(new java.awt.Color(255, 255, 255));
        jLabelIF.setText("IFControl 3.0");

        jLabelIfamLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/IFAM_logo.png"))); // NOI18N
        jLabelIfamLogo.setText("jLabel1");

        jButtonCancelar.setBackground(new java.awt.Color(0, 51, 102));
        jButtonCancelar.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 12)); // NOI18N
        jButtonCancelar.setForeground(new java.awt.Color(255, 255, 255));
        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });

        jLabelProcurarAcao.setBackground(new java.awt.Color(187, 187, 187));
        jLabelProcurarAcao.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 24)); // NOI18N
        jLabelProcurarAcao.setForeground(new java.awt.Color(255, 255, 255));
        jLabelProcurarAcao.setText("Procurar Ação");

        jLabelAutor.setBackground(new java.awt.Color(255, 255, 255));
        jLabelAutor.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 14)); // NOI18N
        jLabelAutor.setForeground(new java.awt.Color(255, 255, 255));
        jLabelAutor.setText("Autor:");

        jLabelTipoAcao.setBackground(new java.awt.Color(255, 255, 255));
        jLabelTipoAcao.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 14)); // NOI18N
        jLabelTipoAcao.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTipoAcao.setText("Tipo ação:");

        jTextFielAutor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFielAutorActionPerformed(evt);
            }
        });

        jButtonProcurar.setBackground(new java.awt.Color(0, 153, 51));
        jButtonProcurar.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 12)); // NOI18N
        jButtonProcurar.setForeground(new java.awt.Color(255, 255, 255));
        jButtonProcurar.setText("Procurar");
        jButtonProcurar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonProcurarActionPerformed(evt);
            }
        });

        jLabelData.setBackground(new java.awt.Color(255, 255, 255));
        jLabelData.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 14)); // NOI18N
        jLabelData.setForeground(new java.awt.Color(255, 255, 255));
        jLabelData.setText("Data:");

        jLabelHora.setBackground(new java.awt.Color(255, 255, 255));
        jLabelHora.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 14)); // NOI18N
        jLabelHora.setForeground(new java.awt.Color(255, 255, 255));
        jLabelHora.setText("Hora:");

        jSpinnerHora.setModel(new javax.swing.SpinnerNumberModel(0, 0, 23, 1));

        jLabelSeparatorHoraIn.setBackground(new java.awt.Color(255, 255, 255));
        jLabelSeparatorHoraIn.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 14)); // NOI18N
        jLabelSeparatorHoraIn.setForeground(new java.awt.Color(255, 255, 255));
        jLabelSeparatorHoraIn.setText(":");

        jSpinnerMinutos.setModel(new javax.swing.SpinnerNumberModel(0, 0, 59, 1));

        jLabelSala.setBackground(new java.awt.Color(255, 255, 255));
        jLabelSala.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 14)); // NOI18N
        jLabelSala.setForeground(new java.awt.Color(255, 255, 255));
        jLabelSala.setText("Sala:");

        jTextFieldSala.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldSalaActionPerformed(evt);
            }
        });

        jComboBoxTipoAcao.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ocupou a sala (OCP)", "Desocupou a sala (DSC)", "Ligou o ar (ARON)", "Desligou o ar (AROFF)", "Ligou a luz (LZON)", "Desligou a luz (LZOFF)", "Ligou a o datashow (DSON)", "Desligou o datashow (DSOFF)", "Adicionou uma sala (addSala)", "Adicionou um agendamento (addAgendamento)", "Editou um agendamento (editAgendamento)", "Deletou um agendamento (deletAgendamento)" }));

        jCheckBox1.setText("Não possui");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelHora)
                    .addComponent(jLabelData))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jDataInicio1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jSpinnerHora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelSeparatorHoraIn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSpinnerMinutos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(38, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelIF, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(411, 411, 411)
                                    .addComponent(jLabelIfamLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jButtonCancelar)))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jButtonProcurar, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(178, 178, 178))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabelTipoAcao)
                            .addComponent(jLabelAutor)
                            .addComponent(jLabelSala))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFielAutor, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBoxTipoAcao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jTextFieldSala, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jCheckBox1)))
                        .addGap(30, 30, 30))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabelProcurarAcao)
                        .addGap(163, 163, 163))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabelIF)
                .addGap(36, 36, 36)
                .addComponent(jLabelProcurarAcao)
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFielAutor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelAutor))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelTipoAcao)
                    .addComponent(jComboBoxTipoAcao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelSala)
                    .addComponent(jTextFieldSala, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCheckBox1))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelData)
                    .addComponent(jDataInicio1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelHora)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jSpinnerHora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabelSeparatorHoraIn)
                        .addComponent(jSpinnerMinutos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addComponent(jButtonProcurar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelIfamLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonCancelar))
                .addContainerGap())
        );

        getContentPane().add(jPanel1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jButtonCancelarActionPerformed

    private void jTextFielAutorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFielAutorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFielAutorActionPerformed

    private void jButtonProcurarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonProcurarActionPerformed
        // TODO add your handling code here:
        // 1. Coletar os parâmetros de pesquisa da tela
        String autorPesquisa = jTextFielAutor.getText();
        String tipoAcaoPesquisa = procurarTipoAcao((String) jComboBoxTipoAcao.getSelectedItem());
        String salaStrPesquisa = jTextFieldSala.getText().trim();

        Calendar dataPesquisa = jDataInicio1.getCalendar();

        // Converte o número da sala para int (considerando 0 se vazio/não possui)
        int nSalaPesquisa = 0;
        boolean pesquisarPorSala = false;
        if (jCheckBox1.isSelected()) {
            nSalaPesquisa = -1; // Pesquisar ações sem sala (nSala = 0)
            pesquisarPorSala = true;
        } else if (!salaStrPesquisa.isEmpty()) {
            try {
                nSalaPesquisa = Integer.parseInt(salaStrPesquisa);
                pesquisarPorSala = true;
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(this, "Número da Sala inválido. Digite um número inteiro.", "Erro de Entrada", JOptionPane.ERROR_MESSAGE);
                return;
            }
        }

        String resp = MainApp.sessao.logs();
        List<Acao> todasAcoes = new ArrayList<>();
        todasAcoes = gs.fromJson(resp, tipoAcao);

        // 3. Filtrar a lista
        List<Acao> acoesSimilares = new ArrayList<>();

        for (Acao acao : todasAcoes) {
            boolean match = true;

            // Filtro por Autor (Login)
            if (!autorPesquisa.isEmpty() && !acao.getLogin().contains(autorPesquisa)) {
                match = false;
                System.out.println("Sem user");
            }

            // Filtro por Tipo de Ação
            if (!acao.getTipoAcao().contains(tipoAcaoPesquisa)) {
                match = false;
                System.out.println("Sem tipo");
            }

            // Filtro por Sala
            if (pesquisarPorSala) {
                if (acao.getnSala() != nSalaPesquisa) {
                    match = false;
                    System.out.println("Sem sala");
                }
            }

            // Filtro por Data e Hora
            if (dataPesquisa != null) {
                dataPesquisa.set(Calendar.HOUR_OF_DAY, 0);
                dataPesquisa.set(Calendar.MINUTE, 0);
                dataPesquisa.set(Calendar.SECOND, 0);
                dataPesquisa.set(Calendar.MILLISECOND, 0);
                Calendar acaoData=acao.getDataAcao();
                acaoData.set(Calendar.HOUR_OF_DAY, 0);
                acaoData.set(Calendar.MINUTE, 0);
                acaoData.set(Calendar.SECOND, 0);
                acaoData.set(Calendar.MILLISECOND, 0);
                if (!dataPesquisa.equals(acaoData)) {
                   match = false; 
                }
            }
            

            if (match) {
                acoesSimilares.add(acao);
            }
        }

        // 4. Exibir os resultados
        if (acoesSimilares.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Nenhuma Ação encontrada com os critérios fornecidos.", "Resultado da Pesquisa", JOptionPane.INFORMATION_MESSAGE);
        } else {
            AcoesEncontradas n = new AcoesEncontradas(acoesSimilares);
            n.setVisible(true);
            dispose();
        }

    }//GEN-LAST:event_jButtonProcurarActionPerformed

    private void jTextFieldSalaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldSalaActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_jTextFieldSalaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PesquisarAcao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PesquisarAcao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PesquisarAcao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PesquisarAcao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PesquisarAcao().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonProcurar;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JComboBox<String> jComboBoxTipoAcao;
    private com.toedter.calendar.JDateChooser jDataInicio1;
    private javax.swing.JLabel jLabelAutor;
    private javax.swing.JLabel jLabelData;
    private javax.swing.JLabel jLabelHora;
    private javax.swing.JLabel jLabelIF;
    private javax.swing.JLabel jLabelIfamLogo;
    private javax.swing.JLabel jLabelProcurarAcao;
    private javax.swing.JLabel jLabelSala;
    private javax.swing.JLabel jLabelSeparatorHoraIn;
    private javax.swing.JLabel jLabelTipoAcao;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSpinner jSpinnerHora;
    private javax.swing.JSpinner jSpinnerMinutos;
    private javax.swing.JTextField jTextFielAutor;
    private javax.swing.JTextField jTextFieldSala;
    // End of variables declaration//GEN-END:variables
}
