/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Aplicacao;

import Modelo.Sala;
import com.google.gson.Gson;
import com.google.gson.reflect.TypeToken;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.util.ArrayList;
import java.util.Collections;
import java.util.Comparator;
import java.util.LinkedList;
import java.util.List;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;

/**
 *
 * @author LENOVO
 */
public class PSala extends javax.swing.JFrame {

    private List<SalaPanel> salasP;
    private List<Sala> salas;
    private Gson gs;
    private java.lang.reflect.Type tipoSala;
    private int salasConectadas;

    /**
     * Creates new form PSala
     */
    public PSala() {

        salasConectadas = 0;
        initComponents();
        this.setExtendedState(MAXIMIZED_BOTH);
        gs = new Gson();
        tipoSala = new TypeToken<List<Sala>>() {
        }.getType();
        adicionarSalas();

        new Thread(new AtulizaDadosSala()).start();

        setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
        addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent e) {
                int resposta = JOptionPane.showConfirmDialog(null, "Deseja realmente sair?", "Alerta", JOptionPane.YES_NO_OPTION);
                if (resposta == JOptionPane.YES_OPTION) {
                    MainApp.sessao.encerrarSessao();
                }
            }
        });

    }

    public void adicionarSalas() {
        Salas.removeAll();
        MainApp.sessao.salas();
        String resp = MainApp.sessao.verificarResposta();
        salas = gs.fromJson(resp, tipoSala);
        salasP= new ArrayList();
        Collections.sort(salas, Comparator.comparingInt(s -> s.getnSala()));
        String salaDes = "Salas desconectadas: ";
        int salaD = 0;
        salasConectadas = salas.size();
        for (Sala s : salas) {
            if (s.isEstadoDaConexao()) {
                String nSala = "Sala " + s.getnSala() + ":";
                SalaPanel ps = new SalaPanel(nSala, s.isEstadoAr(), s.isEstadoDataShow(), s.isEstadoLuzes(), s.isEstadoSala(), s.isPresenca(), s.getnSala());
                Salas.add(ps);
                salasP.add(ps);

            } else {
                salaD += 1;
                salaDes += s.getnSala() + ", ";
            }
        }

        if (salaD > 0) {
            System.out.println(salaDes);
        } else {
            JOptionPane.showMessageDialog(null, "Todas as salas estão conectadas", "Aviso", JOptionPane.INFORMATION_MESSAGE);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelPrincipal = new javax.swing.JPanel();
        jLabelSalas = new javax.swing.JLabel();
        jLabelIF1 = new javax.swing.JLabel();
        jLabelIfamLogo = new javax.swing.JLabel();
        jScrollPaneSala = new javax.swing.JScrollPane();
        Salas = new javax.swing.JPanel();
        jButtonAdicionar = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuLogo = new javax.swing.JMenu();
        jMenuSalas = new javax.swing.JMenu();
        jMenuAgendamento = new javax.swing.JMenu();
        jMenuAcaoes = new javax.swing.JMenu();
        jMenuDIR = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridLayout(1, 0));

        jPanelPrincipal.setBackground(new java.awt.Color(0, 51, 102));

        jLabelSalas.setBackground(new java.awt.Color(255, 255, 255));
        jLabelSalas.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 36)); // NOI18N
        jLabelSalas.setForeground(new java.awt.Color(255, 255, 255));
        jLabelSalas.setText("Salas ");

        jLabelIF1.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 20)); // NOI18N
        jLabelIF1.setForeground(new java.awt.Color(255, 255, 255));
        jLabelIF1.setText("IFControl 3.0");

        jLabelIfamLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/IFAM_logo.png"))); // NOI18N

        jScrollPaneSala.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        Salas.setBackground(new java.awt.Color(0, 51, 102));
        Salas.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(0, 0, 0), null, null));
        Salas.setForeground(new java.awt.Color(0, 0, 0));
        Salas.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 10, 10));
        jScrollPaneSala.setViewportView(Salas);

        jButtonAdicionar.setBackground(new java.awt.Color(0, 51, 102));
        jButtonAdicionar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/mais.png"))); // NOI18N
        jButtonAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAdicionarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelPrincipalLayout = new javax.swing.GroupLayout(jPanelPrincipal);
        jPanelPrincipal.setLayout(jPanelPrincipalLayout);
        jPanelPrincipalLayout.setHorizontalGroup(
            jPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelPrincipalLayout.createSequentialGroup()
                .addGroup(jPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelPrincipalLayout.createSequentialGroup()
                        .addContainerGap(1246, Short.MAX_VALUE)
                        .addGroup(jPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelIfamLogo, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButtonAdicionar, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelPrincipalLayout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(jPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPaneSala, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanelPrincipalLayout.createSequentialGroup()
                                .addComponent(jLabelSalas)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 1020, Short.MAX_VALUE)
                                .addComponent(jLabelIF1)))))
                .addGap(27, 27, 27))
        );
        jPanelPrincipalLayout.setVerticalGroup(
            jPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPrincipalLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelSalas)
                    .addGroup(jPanelPrincipalLayout.createSequentialGroup()
                        .addComponent(jLabelIF1)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonAdicionar)))
                .addGap(16, 16, 16)
                .addComponent(jScrollPaneSala, javax.swing.GroupLayout.DEFAULT_SIZE, 618, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelIfamLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        getContentPane().add(jPanelPrincipal);

        jMenuLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/IFControl3_logoMini.png"))); // NOI18N
        jMenuBar1.add(jMenuLogo);

        jMenuSalas.setText("Salas");
        jMenuSalas.addMenuDragMouseListener(new javax.swing.event.MenuDragMouseListener() {
            public void menuDragMouseDragged(javax.swing.event.MenuDragMouseEvent evt) {
            }
            public void menuDragMouseEntered(javax.swing.event.MenuDragMouseEvent evt) {
                jMenuSalasMenuDragMouseEntered(evt);
            }
            public void menuDragMouseExited(javax.swing.event.MenuDragMouseEvent evt) {
            }
            public void menuDragMouseReleased(javax.swing.event.MenuDragMouseEvent evt) {
            }
        });
        jMenuSalas.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
            }
            public void menuSelected(javax.swing.event.MenuEvent evt) {
                jMenuSalasMenuSelected(evt);
            }
        });
        jMenuSalas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuSalasActionPerformed(evt);
            }
        });
        jMenuBar1.add(jMenuSalas);

        jMenuAgendamento.setText("Agendamentos");
        jMenuAgendamento.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
            }
            public void menuSelected(javax.swing.event.MenuEvent evt) {
                jMenuAgendamentoMenuSelected(evt);
            }
        });
        jMenuAgendamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuAgendamentoActionPerformed(evt);
            }
        });
        jMenuBar1.add(jMenuAgendamento);

        jMenuAcaoes.setText("Ações");
        jMenuAcaoes.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
            }
            public void menuSelected(javax.swing.event.MenuEvent evt) {
                jMenuAcaoesMenuSelected(evt);
            }
        });
        jMenuBar1.add(jMenuAcaoes);

        jMenuDIR.setText("Dispositivos IR");
        jMenuDIR.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
            }
            public void menuSelected(javax.swing.event.MenuEvent evt) {
                jMenuDIRMenuSelected(evt);
            }
        });
        jMenuBar1.add(jMenuDIR);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuSalasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuSalasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuSalasActionPerformed

    private void jMenuAgendamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuAgendamentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuAgendamentoActionPerformed

    private void jMenuAgendamentoMenuSelected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_jMenuAgendamentoMenuSelected
        // TODO add your handling code here:
        dispose();
        MainApp.showPAngendamento();

    }//GEN-LAST:event_jMenuAgendamentoMenuSelected

    private void jMenuSalasMenuDragMouseEntered(javax.swing.event.MenuDragMouseEvent evt) {//GEN-FIRST:event_jMenuSalasMenuDragMouseEntered

    }//GEN-LAST:event_jMenuSalasMenuDragMouseEntered

    private void jMenuSalasMenuSelected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_jMenuSalasMenuSelected
        // TODO add your handling code here:

    }//GEN-LAST:event_jMenuSalasMenuSelected

    private void jMenuAcaoesMenuSelected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_jMenuAcaoesMenuSelected
        // TODO add your handling code here:
        dispose();
        MainApp.showPAAcoes();
    }//GEN-LAST:event_jMenuAcaoesMenuSelected

    private void jMenuDIRMenuSelected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_jMenuDIRMenuSelected
        // TODO add your handling code here:
        dispose();
        MainApp.showPDispositivos();
    }//GEN-LAST:event_jMenuDIRMenuSelected

    private void jButtonAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAdicionarActionPerformed
        // TODO add your handling code here:
        MainApp.showAddSala();
    }//GEN-LAST:event_jButtonAdicionarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PSala.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PSala.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PSala.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PSala.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                PSala sala = new PSala();
                sala.setVisible(true);
            }
        });
    }

    private class AtulizaDadosSala implements Runnable {

        public SalaPanel procurarSP(Sala sala) {
            for (SalaPanel sp : salasP) {
                if (sp.getN()==sala.getnSala()) {
                    return sp;
                }
            }
            System.out.println("Não foi posssivel encontrar nem um Panel para a sala: " + sala.getnSala());
            return null;
        }

        @Override
        public void run() {
            while (isDisplayable()) {
                String resposta = MainApp.sessao.verificarResposta();
                if (resposta.contains("nSala")) {
                    salas = gs.fromJson(resposta, tipoSala);
                    Collections.sort(salas, Comparator.comparingInt(s -> s.getnSala()));
                    SwingUtilities.invokeLater(new Runnable() {
                        @Override
                        public void run() {
                            for (Sala sala : salas) {
                                if (sala.isEstadoDaConexao()) {
                                    SalaPanel newSp = procurarSP(sala);
                                    if (newSp == null) {
                                        String nSala = "Sala " + sala.getnSala() + ":";
                                        SalaPanel ps = new SalaPanel(nSala, sala.isEstadoAr(), sala.isEstadoDataShow(), sala.isEstadoLuzes(),
                                                sala.isEstadoSala(), sala.isPresenca(), sala.getnSala());
                                        Salas.add(ps);
                                    } else {
                                        newSp.atualizar(sala.isEstadoSala(), sala.isEstadoDataShow(), sala.isEstadoLuzes(),
                                                sala.isEstadoAr(), sala.isPresenca());
                                    }
                                }
                            }
                        }
                    });
                }
                try {
                    Thread.sleep(1000);
                } catch (InterruptedException ex) {
                    System.out.println("Erro ao atualizar");
                }

            }
            System.exit(0);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Salas;
    private javax.swing.JButton jButtonAdicionar;
    private javax.swing.JLabel jLabelIF1;
    private javax.swing.JLabel jLabelIfamLogo;
    private javax.swing.JLabel jLabelSalas;
    private javax.swing.JMenu jMenuAcaoes;
    private javax.swing.JMenu jMenuAgendamento;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuDIR;
    private javax.swing.JMenu jMenuLogo;
    private javax.swing.JMenu jMenuSalas;
    private javax.swing.JPanel jPanelPrincipal;
    private javax.swing.JScrollPane jScrollPaneSala;
    // End of variables declaration//GEN-END:variables
}
