/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Aplicacao;

import java.util.Collections;
import java.util.Comparator;
import javax.swing.SwingUtilities;

/**
 *
 * @author LENOVO
 */
public class Sala extends javax.swing.JFrame {
    private Sala sala;
    /**
     * Creates new form Sala
     */
    public Sala() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelPrincipal = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabelIfamLogo = new javax.swing.JLabel();
        jLabelTemperatura = new javax.swing.JLabel();
        jLabelHumidade = new javax.swing.JLabel();
        jLabelPresença = new javax.swing.JLabel();
        jLabelAr = new javax.swing.JLabel();
        jLabelLuz = new javax.swing.JLabel();
        jLabelDS1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabelN = new javax.swing.JLabel();
        jLabelSala = new javax.swing.JLabel();
        jLabelTemperaturaValor = new javax.swing.JLabel();
        jLabelHumidadeValor = new javax.swing.JLabel();
        jLabelHumidadeValor1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        comboBoxTemperatura = new javax.swing.JComboBox<>();
        jLabelTemperatura1 = new javax.swing.JLabel();
        jLabelTemperatura2 = new javax.swing.JLabel();
        jLabelModo = new javax.swing.JLabel();
        comboBoxModo = new javax.swing.JComboBox<>();
        jLabelDS2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(800, 600));
        getContentPane().setLayout(new java.awt.GridLayout(1, 0));

        jPanelPrincipal.setBackground(new java.awt.Color(0, 51, 102));
        jPanelPrincipal.setPreferredSize(new java.awt.Dimension(800, 800));
        jPanelPrincipal.setLayout(new java.awt.GridLayout(1, 3));

        jPanel1.setBackground(new java.awt.Color(0, 51, 102));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        jLabelIfamLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/IFAM_logo.png"))); // NOI18N
        jLabelIfamLogo.setText("jLabel1");

        jLabelTemperatura.setBackground(new java.awt.Color(255, 255, 255));
        jLabelTemperatura.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 18)); // NOI18N
        jLabelTemperatura.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTemperatura.setText("Temperatura:");
        jLabelTemperatura.setToolTipText("");

        jLabelHumidade.setBackground(new java.awt.Color(255, 255, 255));
        jLabelHumidade.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 18)); // NOI18N
        jLabelHumidade.setForeground(new java.awt.Color(255, 255, 255));
        jLabelHumidade.setText("Humidade:");
        jLabelHumidade.setToolTipText("");

        jLabelPresença.setBackground(new java.awt.Color(255, 255, 255));
        jLabelPresença.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 18)); // NOI18N
        jLabelPresença.setForeground(new java.awt.Color(255, 255, 255));
        jLabelPresença.setText("Presença:");
        jLabelPresença.setToolTipText("");

        jLabelAr.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/ar-condicionado-on (1).png"))); // NOI18N

        jLabelLuz.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/luz-on (1).png"))); // NOI18N

        jLabelDS1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/data-show-on (1).png"))); // NOI18N

        jPanel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabelN.setBackground(new java.awt.Color(255, 255, 255));
        jLabelN.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 36)); // NOI18N
        jLabelN.setForeground(new java.awt.Color(255, 255, 255));
        jLabelN.setText("X");

        jLabelSala.setBackground(new java.awt.Color(255, 255, 255));
        jLabelSala.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 36)); // NOI18N
        jLabelSala.setForeground(new java.awt.Color(255, 255, 255));
        jLabelSala.setText("Sala");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabelSala)
                .addGap(18, 18, 18)
                .addComponent(jLabelN)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelSala, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelN, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        jLabelTemperaturaValor.setBackground(new java.awt.Color(255, 255, 255));
        jLabelTemperaturaValor.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 18)); // NOI18N
        jLabelTemperaturaValor.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTemperaturaValor.setText("XX");
        jLabelTemperaturaValor.setToolTipText("");

        jLabelHumidadeValor.setBackground(new java.awt.Color(255, 255, 255));
        jLabelHumidadeValor.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 18)); // NOI18N
        jLabelHumidadeValor.setForeground(new java.awt.Color(255, 255, 255));
        jLabelHumidadeValor.setText("XX");
        jLabelHumidadeValor.setToolTipText("");

        jLabelHumidadeValor1.setBackground(new java.awt.Color(255, 255, 255));
        jLabelHumidadeValor1.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 18)); // NOI18N
        jLabelHumidadeValor1.setForeground(new java.awt.Color(255, 255, 255));
        jLabelHumidadeValor1.setText("XX");
        jLabelHumidadeValor1.setToolTipText("");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelIfamLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabelAr)
                                .addGap(43, 43, 43)
                                .addComponent(jLabelLuz)
                                .addGap(43, 43, 43)
                                .addComponent(jLabelDS1))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabelHumidade)
                                    .addGap(18, 18, 18)
                                    .addComponent(jLabelHumidadeValor))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabelTemperatura)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jLabelTemperaturaValor))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                    .addGap(70, 70, 70)
                                    .addComponent(jLabelPresença)
                                    .addGap(18, 18, 18)
                                    .addComponent(jLabelHumidadeValor1))))))
                .addGap(20, 65, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelTemperatura)
                    .addComponent(jLabelTemperaturaValor))
                .addGap(50, 50, 50)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelHumidade)
                            .addComponent(jLabelHumidadeValor))
                        .addGap(50, 50, 50)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelPresença)
                            .addComponent(jLabelHumidadeValor1))
                        .addGap(84, 84, 84)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabelAr)
                            .addComponent(jLabelLuz)))
                    .addComponent(jLabelDS1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                .addComponent(jLabelIfamLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanelPrincipal.add(jPanel1);

        jPanel2.setBackground(new java.awt.Color(0, 51, 102));
        jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));

        comboBoxTemperatura.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 14)); // NOI18N
        comboBoxTemperatura.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "16", "17", "18", "19", "20", "21", "22", "23", "24", "25" }));
        comboBoxTemperatura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxTemperaturaActionPerformed(evt);
            }
        });

        jLabelTemperatura1.setBackground(new java.awt.Color(255, 255, 255));
        jLabelTemperatura1.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 24)); // NOI18N
        jLabelTemperatura1.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTemperatura1.setText("Ar-condicionado");
        jLabelTemperatura1.setToolTipText("");

        jLabelTemperatura2.setBackground(new java.awt.Color(255, 255, 255));
        jLabelTemperatura2.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 18)); // NOI18N
        jLabelTemperatura2.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTemperatura2.setText("Temperatura:");
        jLabelTemperatura2.setToolTipText("");

        jLabelModo.setBackground(new java.awt.Color(255, 255, 255));
        jLabelModo.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 18)); // NOI18N
        jLabelModo.setForeground(new java.awt.Color(255, 255, 255));
        jLabelModo.setText("Modo:");
        jLabelModo.setToolTipText("");

        comboBoxModo.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 14)); // NOI18N
        comboBoxModo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cool", "Fan", "Auto", "Dry" }));
        comboBoxModo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxModoActionPerformed(evt);
            }
        });

        jLabelDS2.setBackground(new java.awt.Color(255, 255, 255));
        jLabelDS2.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 24)); // NOI18N
        jLabelDS2.setForeground(new java.awt.Color(255, 255, 255));
        jLabelDS2.setText("Data-show");
        jLabelDS2.setToolTipText("");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(58, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelModo)
                    .addComponent(jLabelTemperatura2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(comboBoxTemperatura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboBoxModo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(170, 170, 170))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelDS2)
                    .addComponent(jLabelTemperatura1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabelTemperatura1)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboBoxTemperatura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelTemperatura2))
                .addGap(33, 33, 33)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelModo)
                    .addComponent(comboBoxModo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(85, 85, 85)
                .addComponent(jLabelDS2)
                .addContainerGap(282, Short.MAX_VALUE))
        );

        jPanelPrincipal.add(jPanel2);

        getContentPane().add(jPanelPrincipal);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void comboBoxTemperaturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxTemperaturaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboBoxTemperaturaActionPerformed

    private void comboBoxModoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxModoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboBoxModoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Sala.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Sala.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Sala.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Sala.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Sala().setVisible(true);
            }
        });
    }
     private class AtulizaDadosSala implements Runnable {

        @Override
        public void run() {
            while (isDisplayable()) {
                String resposta = MainApp.sessao.verificarResposta();
                if (resposta.contains("nSala")) {
                    salas = gs.fromJson(resposta, tipoSala);
                    Collections.sort(salas, Comparator.comparingInt(s -> s.getnSala()));
                    SwingUtilities.invokeLater(new Runnable() {
                        @Override
                        public void run() {
                            for (Modelo.Sala sala : salas) {
                                if (sala.isEstadoDaConexao()) {
                                    SalaPanel newSp = procurarSP(sala);
                                    if (newSp == null) {
                                        String nSala = "Sala " + sala.getnSala() + ":";
                                        SalaPanel ps = new SalaPanel(nSala, sala.isEstadoAr(), sala.isEstadoDataShow(), sala.isEstadoLuzes(),
                                                sala.isEstadoSala(), sala.isPresenca(), sala.getnSala());
                                        Salas.add(ps);
                                    } else {
                                        newSp.atualizar(sala.isEstadoSala(), sala.isEstadoDataShow(), sala.isEstadoLuzes(),
                                                sala.isEstadoAr(), sala.isPresenca());
                                    }
                                }
                            }
                        }
                    });
                }
                try {
                    Thread.sleep(1000);
                } catch (InterruptedException ex) {
                    System.out.println("Erro ao atualizar");
                }

            }
            System.exit(0);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> comboBoxModo;
    private javax.swing.JComboBox<String> comboBoxTemperatura;
    private javax.swing.JLabel jLabelAr;
    private javax.swing.JLabel jLabelDS1;
    private javax.swing.JLabel jLabelDS2;
    private javax.swing.JLabel jLabelHumidade;
    private javax.swing.JLabel jLabelHumidadeValor;
    private javax.swing.JLabel jLabelHumidadeValor1;
    private javax.swing.JLabel jLabelIfamLogo;
    private javax.swing.JLabel jLabelLuz;
    private javax.swing.JLabel jLabelModo;
    private javax.swing.JLabel jLabelN;
    private javax.swing.JLabel jLabelPresença;
    private javax.swing.JLabel jLabelSala;
    private javax.swing.JLabel jLabelTemperatura;
    private javax.swing.JLabel jLabelTemperatura1;
    private javax.swing.JLabel jLabelTemperatura2;
    private javax.swing.JLabel jLabelTemperaturaValor;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanelPrincipal;
    // End of variables declaration//GEN-END:variables
}

