/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Aplicacao;

import Modelo.Sala;
import java.awt.Color;
import javax.swing.ImageIcon;
import javax.swing.SwingUtilities;

/**
 *
 * @author LENOVO
 */
public class SalaPanel extends javax.swing.JPanel {
    
    protected int nsala;
    protected static boolean salaAberta=false;
    private FrameSala novaSala;
    
    /**
     * Creates new form SalaPanel
     */
    public SalaPanel(String textoNSala, boolean estadoAr, boolean estadoDS, boolean estadoLuzes,
    boolean estadoSala, boolean presenca, int nsala) {
        initComponents();
        jLabelNSala.setText(textoNSala);
        
        atualizar(estadoSala, estadoDS, estadoLuzes, estadoAr, presenca);
        this.nsala=nsala;
        
    }
    
    public boolean getSalaAberta(){
        return salaAberta;
    }
    
    public void atualizar(boolean estadoSala, boolean estadoDS, boolean estadoLuzes,
            boolean estadoAr, boolean presenca){
        
        if(estadoAr){
            jLabelAr.setText("ON");
            jLabelAr.setForeground(new Color(0,153,51));
        }else{
            jLabelAr.setText("OFF");
            jLabelAr.setForeground(new Color(255,0,0));
        }
        if(estadoDS){
            jLabelDS.setText("ON");
            jLabelDS.setForeground(new Color(0,153,51));
        }else{
            jLabelDS.setText("OFF");
            jLabelDS.setForeground(new Color(255,0,0));
        }
        if(estadoLuzes){
            jLabelLuzes.setText("ON");
            jLabelLuzes.setForeground(new Color(0,153,51));
        }else{
            jLabelLuzes.setText("OFF");
            jLabelLuzes.setForeground(new Color(255,0,0));
        }
        
        if(estadoSala){
            jPanelEstadoSala.setBackground(Color.red);
            jButtonEntrar.setEnabled(!estadoSala);
        }else{
            jPanelEstadoSala.setBackground(Color.green);
            jButtonEntrar.setEnabled(!estadoSala);
        }
        
        if(presenca){
            jLabelMovimento.setIcon(new ImageIcon(getClass().getResource("/Imagens/movimento.PNG")));
        }else{
            jLabelMovimento.setIcon(new ImageIcon(getClass().getResource("/Imagens/repouso.PNG")));
        }
    }
    

    public int getN() {
        return nsala;
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelNSala = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jPanelEstadoSala = new javax.swing.JPanel();
        jButtonEntrar = new javax.swing.JButton();
        jLabelAr = new javax.swing.JLabel();
        jLabelDS = new javax.swing.JLabel();
        jLabelLuzes = new javax.swing.JLabel();
        jLabelMovimento = new javax.swing.JLabel();

        setBackground(new java.awt.Color(153, 153, 153));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        setPreferredSize(new java.awt.Dimension(150, 180));

        jLabelNSala.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 14)); // NOI18N
        jLabelNSala.setForeground(new java.awt.Color(0, 0, 0));
        jLabelNSala.setText("Sala 1");

        jLabel9.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("Ar-cod.:");

        jLabel10.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("Data-Show:");

        jLabel11.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setText("Luzes:");

        jPanelEstadoSala.setBackground(new java.awt.Color(0, 204, 51));
        jPanelEstadoSala.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanelEstadoSala.setPreferredSize(new java.awt.Dimension(15, 15));

        javax.swing.GroupLayout jPanelEstadoSalaLayout = new javax.swing.GroupLayout(jPanelEstadoSala);
        jPanelEstadoSala.setLayout(jPanelEstadoSalaLayout);
        jPanelEstadoSalaLayout.setHorizontalGroup(
            jPanelEstadoSalaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 13, Short.MAX_VALUE)
        );
        jPanelEstadoSalaLayout.setVerticalGroup(
            jPanelEstadoSalaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 13, Short.MAX_VALUE)
        );

        jButtonEntrar.setBackground(new java.awt.Color(204, 204, 204));
        jButtonEntrar.setForeground(new java.awt.Color(0, 0, 0));
        jButtonEntrar.setText("Entrar");
        jButtonEntrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEntrarActionPerformed(evt);
            }
        });

        jLabelAr.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 12)); // NOI18N
        jLabelAr.setForeground(new java.awt.Color(0, 153, 51));
        jLabelAr.setText("ON");

        jLabelDS.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 12)); // NOI18N
        jLabelDS.setForeground(new java.awt.Color(0, 153, 51));
        jLabelDS.setText("ON");

        jLabelLuzes.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 12)); // NOI18N
        jLabelLuzes.setForeground(new java.awt.Color(0, 153, 51));
        jLabelLuzes.setText("ON");

        jLabelMovimento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/movimento.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabelNSala)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelMovimento))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11)
                            .addComponent(jPanelEstadoSala, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelAr)
                            .addComponent(jLabelDS)
                            .addComponent(jLabelLuzes)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(jButtonEntrar)))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelMovimento, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelNSala))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jLabelAr))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jLabelDS))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jLabelLuzes))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelEstadoSala, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonEntrar)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonEntrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEntrarActionPerformed
        // TODO add your handling code here:
        salaAberta=true;
        novaSala= new FrameSala(nsala);
        
    }//GEN-LAST:event_jButtonEntrarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonEntrar;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelAr;
    private javax.swing.JLabel jLabelDS;
    private javax.swing.JLabel jLabelLuzes;
    private javax.swing.JLabel jLabelMovimento;
    private javax.swing.JLabel jLabelNSala;
    private javax.swing.JPanel jPanelEstadoSala;
    // End of variables declaration//GEN-END:variables
}
